import {syncPreventiveAlerts} from './preventive-alerts';
import { prisma } from '@/lib/prisma';
import {syncMaintenanceAlerts} from './maintenance-alerts';
import { currency, date, integer } from '@/lib/utils';
import type { DataRow } from '@/components/data-table';
type ModuleData = { description: string; columns: string[]; rows: DataRow[] };
export async function getModuleData(slug: string): Promise<ModuleData | null> {
  if(slug==='alertas'){await syncMaintenanceAlerts();await syncPreventiveAlerts();}
  const now = new Date();
  switch (slug) {
    case 'frota': return { description: 'Veículos, disponibilidade e acesso ao checklist por QR Code.', columns: ['Placa','Modelo','Ano','Perfil','Cubagem','Quilometragem'], rows: (await prisma.vehicle.findMany({ orderBy: { plate: 'asc' } })).map(v => ({ id: v.id, cells: [v.plate,v.model,String(v.year),v.profile ?? v.category,v.cargoVolumeM3 === null ? 'Não informado' : `${Number(v.cargoVolumeM3).toLocaleString('pt-BR')} m³`,v.mileage === null ? 'Não informado' : `${integer(v.mileage)} km`], status: v.operationalStatus === 'CLEAR' ? v.status : v.operationalStatus, href: `/frota/${v.plate}` })) };
    case 'checklists': return { description: 'Inspeções enviadas pelos motoristas, centralizadas na operação.', columns: ['Veículo','Motorista','Quilometragem','Realizado em','Conformidade','Observações'], rows: (await prisma.checklist.findMany({ include: { vehicle: true }, orderBy: { submittedAt: 'desc' } })).map(c => ({ id: c.id, cells: [c.vehicle.plate,c.driverName,`${integer(c.mileage)} km`,date(c.submittedAt),c.conformityPercentage === null ? 'Não avaliado' : `${Number(c.conformityPercentage).toLocaleString('pt-BR')}%`,c.notes || 'Sem observações'], status: c.result, href: `/checklists/${c.id}` })) };
    case 'ocorrencias': return { description: 'Acompanhe falhas e pendências operacionais por veículo.', columns: ['Número','Ocorrência','Veículo','Prioridade','Abertura'], rows: (await prisma.incident.findMany({ include: { vehicle: true }, orderBy: [{ priority: 'desc' }, { createdAt: 'desc' }] })).map(i => ({ id: i.id, cells: [i.publicNumber ?? `OC-${String(i.number).padStart(6,'0')}`,i.title,i.vehicle.plate,priority(i.priority),date(i.openedAt)], status: i.status, href: `/ocorrencias/${i.id}` })) };
    case 'alertas': return { description: 'Concentre a atenção nos eventos que exigem uma ação da Frota.', columns: ['Alerta','Veículo','Orientação','Situação'], rows: (await prisma.alert.findMany({ include: { vehicle: true }, orderBy: [{ priority: 'desc' }, { createdAt: 'desc' }] })).map(a => ({ id: a.id, cells: [a.title,a.vehicle?.plate ?? 'Operação',a.description,a.status === 'OPEN' ? 'Pendente' : a.status === 'COMPLETED' ? 'Concluído' : a.status === 'CANCELED' ? 'Cancelado' : 'Em andamento'], status: a.priority, href: `/alertas/${a.id}` })) };
    case 'manutencoes': return { description: 'Ordens de serviço, programação e custos de manutenção.', columns: ['Serviço','Veículo','Tipo','Programação','Custo previsto'], rows: (await prisma.maintenance.findMany({ include: { vehicle: true }, orderBy: { scheduledAt: 'desc' } })).map(m => ({ id: m.id, cells: [m.title,m.vehicle.plate,m.type,m.scheduledAt ? date(m.scheduledAt) : 'Não programada',currency(Number(m.cost))], status: m.status })) };
    case 'preventivas': return { description: 'Vencimentos por data e quilometragem para antecipar as paradas.', columns: ['Serviço','Veículo','Prazo','Quilometragem limite'], rows: (await prisma.preventive.findMany({ include: { vehicle: true }, orderBy: { dueAt: 'asc' } })).map(p => ({ id: p.id, cells: [p.title,p.vehicle.plate,date(p.dueAt),`${integer(p.dueMileage)} km`], status: p.completedAt ? 'COMPLETED' : p.dueAt < now || (p.vehicle.mileage !== null && p.vehicle.mileage >= p.dueMileage) ? 'OVERDUE' : p.dueAt.getTime()-now.getTime() <= 7*86400000 ? 'MEDIUM' : 'LOW' })) };
    case 'pneus': return { description: 'Identificação, posição e condição dos pneus da operação.', columns: ['Identificação','Descrição','Veículo','Posição','Sulco'], rows: (await prisma.tire.findMany({ include: { vehicle: true }, orderBy: { serial: 'asc' } })).map(t => ({ id: t.id, cells: [t.serial,t.brand,t.vehicle?.plate ?? 'Estoque',t.position,`${t.treadMm} mm`], status: t.status === 'Atenção' ? 'MEDIUM' : 'IN_USE' })) };
    case 'compras': return { description: 'Solicitações de materiais e serviços para a frota.', columns: ['Pedido','Descrição','Veículo','Fornecedor','Valor'], rows: (await prisma.purchaseOrder.findMany({ include: { vehicle: true, supplier: true }, orderBy: { createdAt: 'desc' } })).map(p => ({ id: p.id, cells: [p.orderNumber??'Ainda não gerado',p.description,p.vehicle?.plate ?? '—',p.supplier?.name ?? 'Não definido',p.amountKnown?currency(Number(p.amount)):'Não informado'], status: p.status, href: `/compras/${p.id}` })) };
    case 'fornecedores': return { description: 'Parceiros de manutenção, peças e serviços.', columns: ['Razão social','CNPJ','Especialidade','Telefone'], rows: (await prisma.supplier.findMany({ orderBy: { name: 'asc' } })).map(s => ({ id: s.id, cells: [s.name,s.taxId,s.specialty,s.phone], status: s.active ? s.status : 'INACTIVE' })) };
    case 'motoristas': return { description: 'Condutores da operação e validade das habilitações.', columns: ['Nome','Matrícula','Telefone','Categoria CNH','Validade CNH'], rows: (await prisma.driver.findMany({ orderBy: { name: 'asc' } })).map(d => ({ id: d.id, cells: [d.name,d.employeeId,d.phone ?? 'Não informado',d.category,date(d.expiresAt)], status: !d.active ? 'INACTIVE' : d.status !== 'ACTIVE' ? d.status : d.expiresAt < now ? 'OVERDUE' : d.expiresAt.getTime()-now.getTime() < 30*86400000 ? 'MEDIUM' : 'ACTIVE' })) };
    case 'documentos': return { description: 'Vencimentos e pendências de documentos dos veículos.', columns: ['Documento','Veículo','Validade'], rows: (await prisma.document.findMany({ include: { vehicle: true }, orderBy: { expiresAt: 'asc' } })).map(d => ({ id: d.id, cells: [d.title,d.vehicle.plate,date(d.expiresAt)], status: d.expiresAt < now ? 'OVERDUE' : d.expiresAt.getTime()-now.getTime() <= 30*86400000 ? 'MEDIUM' : 'OK' })) };
    default: return null;
  }
}
function priority(value: string) { return ({ LOW: 'Informação', MEDIUM: 'Atenção', HIGH: 'Urgente', CRITICAL: 'Crítico' } as Record<string,string>)[value] ?? value; }
