import {Prisma} from '@prisma/client';
import {prisma} from './prisma';
export type VehicleTimelineEvent={id:string;at:Date;kind:string;title:string;detail:string;actor:string;href:string};
/** Union the source records without recreating, deleting or rewriting their histories. */
export async function getVehicleTimeline(vehicleId:string,page=1,size=30){
 const events=Prisma.sql`WITH related_purchases AS (
 SELECT p.id FROM "PurchaseOrder" p WHERE p."vehicleId"=${vehicleId}
 OR EXISTS(SELECT 1 FROM "Incident" i WHERE i."purchaseOrderId"=p.id AND i."vehicleId"=${vehicleId})
 OR EXISTS(SELECT 1 FROM "Maintenance" m WHERE m."purchaseOrderId"=p.id AND m."vehicleId"=${vehicleId})
 ), events AS (
 SELECT 'vehicle:'||v.id AS id,v."createdAt" AS at,'Cadastro'::text AS kind,'Veículo cadastrado'::text AS title,v.model AS detail,'Sistema'::text AS actor,'/frota/'||v.plate AS href FROM "Vehicle" v WHERE v.id=${vehicleId}
 UNION ALL SELECT 'checklist:'||c.id,c."submittedAt",'Checklist','Checklist realizado',c.mileage::text||' km · '||CASE WHEN c."hasProblem" THEN 'Com não conformidade' ELSE 'Sem problema informado' END,c."driverName",'/checklists/'||c.id FROM "Checklist" c WHERE c."vehicleId"=${vehicleId}
 UNION ALL SELECT 'problem:'||a.id,COALESCE(e."evaluatedAt",c."submittedAt"),'Problema','Problema identificado: '||COALESCE(NULLIF(a."itemLabel",''),a.item),COALESCE(a."problemType",a.notes,''),c."driverName",'/checklists/'||c.id FROM "ChecklistAnswer" a JOIN "Checklist" c ON c.id=a."checklistId" LEFT JOIN "ChecklistEvaluation" e ON e."answerId"=a.id WHERE c."vehicleId"=${vehicleId} AND a.answer='ISSUE'
 UNION ALL SELECT 'incident:'||i.id,i."openedAt",'Ocorrência',i."publicNumber"||' aberta',i.title,'Registro de ocorrência','/ocorrencias/'||i.id FROM "Incident" i WHERE i."vehicleId"=${vehicleId}
 UNION ALL SELECT 'incident-event:'||e.id,e."createdAt",'Ocorrência','Atendimento de '||i."publicNumber",e.note,e.actor,'/ocorrencias/'||i.id FROM "IncidentEvent" e JOIN "Incident" i ON i.id=e."incidentId" WHERE i."vehicleId"=${vehicleId} AND e.kind NOT IN ('CREATED','CHECKLIST','DETECTED','MIGRATED')
 UNION ALL SELECT 'maintenance:'||m.id,m."createdAt",'Manutenção','Manutenção cadastrada',m.title,'Registro de manutenção','/manutencoes/'||m.id FROM "Maintenance" m WHERE m."vehicleId"=${vehicleId}
 UNION ALL SELECT 'maintenance-entry:'||m.id,m."enteredAt",'Manutenção','Entrada em manutenção',m.title,'Data de entrada informada','/manutencoes/'||m.id FROM "Maintenance" m WHERE m."vehicleId"=${vehicleId} AND m."enteredAt" IS NOT NULL
 UNION ALL SELECT 'maintenance-event:'||e.id,e."createdAt",'Manutenção',CASE WHEN e."after"->>'stage'='IN_SERVICE' AND e."before"->>'stage' IS DISTINCT FROM 'IN_SERVICE' THEN 'Manutenção iniciada' WHEN e."after"->>'stage'='DONE' AND e."before"->>'stage' IS DISTINCT FROM 'DONE' THEN 'Manutenção concluída' ELSE 'Atendimento de manutenção' END,m.title||' · '||e.note,e.actor,'/manutencoes/'||m.id FROM "MaintenanceEvent" e JOIN "Maintenance" m ON m.id=e."maintenanceId" WHERE m."vehicleId"=${vehicleId} AND e."before" IS NOT NULL
 UNION ALL SELECT 'purchase:'||p.id,p."requestedAt",'Compra','Compra solicitada'||CASE WHEN p."orderNumber" IS NULL THEN '' ELSE ': '||p."orderNumber" END,p.description,COALESCE(s.name,'Solicitante não informado'),'/compras/'||p.id FROM "PurchaseOrder" p LEFT JOIN "StaffMember" s ON s.id=p."requesterId" WHERE p.id IN (SELECT id FROM related_purchases)
 UNION ALL SELECT 'purchase-event:'||e.id,e."createdAt",'Compra','Atendimento de compras',e.note,e.actor,'/compras/'||e."purchaseId" FROM "PurchaseEvent" e WHERE e."purchaseId" IN (SELECT id FROM related_purchases) OR e."before"->>'vehicleId'=${vehicleId} OR e."after"->>'vehicleId'=${vehicleId}
 UNION ALL SELECT 'sc:'||s.id,s."createdAt",'SC','SC '||s.number||' criada',s.description,'SC relacionada à operação','/compras?q='||s.number FROM "PurchaseRequisition" s WHERE EXISTS(SELECT 1 FROM "PurchaseOrder" p WHERE p."requisitionId"=s.id AND p.id IN (SELECT id FROM related_purchases)) OR EXISTS(SELECT 1 FROM "Incident" i WHERE i."requisitionId"=s.id AND i."vehicleId"=${vehicleId}) OR EXISTS(SELECT 1 FROM "Maintenance" m WHERE m."requisitionId"=s.id AND m."vehicleId"=${vehicleId})
 UNION ALL SELECT 'restriction:'||e.id,e."createdAt",'Restrição',CASE WHEN e.decision='RELEASED' AND e."after"->>'operationalStatusAfter'='CLEAR' AND e."after"->>'vehicleStatusAfter'='AVAILABLE' THEN 'Veículo liberado' WHEN e.decision='RELEASED' THEN 'Restrição liberada' WHEN e.decision='BLOCKED' THEN 'Veículo bloqueado' ELSE 'Restrição aguardando avaliação' END,r.reason||' · '||e.notes,e.actor,'/frota/'||r."vehicleId"||'#restricoes' FROM "RestrictionEvent" e JOIN "VehicleRestriction" r ON r.id=e."restrictionId" WHERE r."vehicleId"=${vehicleId}
 UNION ALL SELECT 'preventive:'||e.id,e."createdAt",'Preventiva','Plano preventivo atualizado',e.note,e.actor,'/preventivas/'||p."vehicleId" FROM "PreventivePlanEvent" e JOIN "PreventivePlan" p ON p.id=e."planId" WHERE p."vehicleId"=${vehicleId}
 UNION ALL SELECT 'legacy-preventive:'||p.id,COALESCE(p."completedAt",p."createdAt"),'Preventiva',CASE WHEN p."completedAt" IS NOT NULL THEN 'Preventiva concluída' ELSE 'Preventiva programada' END,p.title,'Programação registrada','/preventivas?record='||p.id FROM "Preventive" p WHERE p."vehicleId"=${vehicleId}
 UNION ALL SELECT 'mileage:'||r.id,r."createdAt",'Hodômetro',CASE WHEN r.accepted THEN 'Leitura de KM registrada' ELSE 'Possível erro de quilometragem' END,r.mileage::text||' km · anterior: '||COALESCE(r."previousMileage"::text,'não informado'),r.actor,'/preventivas/'||r."vehicleId" FROM "MileageReading" r WHERE r."vehicleId"=${vehicleId}
 UNION ALL SELECT 'fuel:'||f.id,f."fueledAt",'Abastecimento','Abastecimento registrado',replace(f.liters::text,'.',',')||' L · R$ '||replace(f.amount::text,'.',',')||' · '||f.station,f.actor,'/frota/'||f."vehicleId"||'?tab=abastecimentos' FROM "FuelRecord" f WHERE f."vehicleId"=${vehicleId}
 UNION ALL SELECT 'document:'||d.id,d."createdAt",'Documento','Documento cadastrado',d.title,'Cadastro de documento','/frota/'||d."vehicleId"||'?tab=documentos' FROM "Document" d WHERE d."vehicleId"=${vehicleId}
 UNION ALL SELECT 'alert-event:'||e.id,e."createdAt",'Alerta',a.title,e.note,e.actor,'/alertas/'||a.id FROM "AlertEvent" e JOIN "Alert" a ON a.id=e."alertId" WHERE a."vehicleId"=${vehicleId}
 UNION ALL SELECT 'qr-event:'||e.id,e."createdAt",'QR Code',CASE WHEN e."previousFingerprint" IS NULL THEN 'Acesso de checklist preservado' ELSE 'QR Code do checklist regenerado' END,e.reason,e.actor,'/frota/'||e."vehicleId"||'#qr-checklist' FROM "VehicleQrEvent" e WHERE e."vehicleId"=${vehicleId}
 UNION ALL SELECT 'tire:'||t.id,t."createdAt",'Pneu','Pneu cadastrado (vínculo atual)',t.serial||' · '||t.brand,'Cadastro de pneu','/frota/'||t."vehicleId"||'?tab=pneus' FROM "Tire" t WHERE t."vehicleId"=${vehicleId}
 )`;
 const [rows,count]=await prisma.$transaction([prisma.$queryRaw<VehicleTimelineEvent[]>(Prisma.sql`${events} SELECT * FROM events ORDER BY at DESC,id DESC LIMIT ${size} OFFSET ${(page-1)*size}`),prisma.$queryRaw<{total:number}[]>(Prisma.sql`${events} SELECT count(*)::int AS total FROM events`)],{isolationLevel:'RepeatableRead'});
 return {rows:rows.map(e=>({...e,href:e.id.startsWith('sc:')?`/compras?q=${encodeURIComponent(e.title.slice(3,-7))}`:e.href})),total:count[0]?.total??0};
}
