import Link from 'next/link';
import {VehicleRestrictions} from '@/components/vehicle-restrictions';
import {RestrictionBanner} from '@/components/restriction-banner';
import {notFound} from 'next/navigation';
import {prisma} from '@/lib/prisma';
import {ChecklistTrace} from '@/components/checklist-trace';
import {StatusBadge} from '@/components/status-badge';
import {IncidentStageBadge} from '@/components/incident-stage';
import {IncidentTimeline} from '@/components/incident-timeline';
import {IncidentEditor} from '@/components/incident-editor';
import {incidentCategories,incidentOrigins,incidentDate,openTime} from '@/lib/incidents';
export const dynamic='force-dynamic';
export default async function IncidentPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const incident=await prisma.incident.findUnique({where:{id},include:{vehicle:true,responsible:true,supplier:true,requisition:true,purchaseOrder:true,maintenance:true,evaluation:true,events:{orderBy:{createdAt:'asc'}},attachments:{select:{id:true,fileName:true,sizeBytes:true,actor:true,createdAt:true},orderBy:{createdAt:'asc'}}}});if(!incident)notFound();
 const [staff,suppliers,requisitions,orders,maintenance]=await Promise.all([
  prisma.staffMember.findMany({where:{OR:[{active:true},{id:incident.responsibleId??''}]},orderBy:{name:'asc'}}),
  prisma.supplier.findMany({where:{OR:[{active:true,status:'ACTIVE'},{id:incident.supplierId??''}]},orderBy:{name:'asc'}}),
  prisma.purchaseRequisition.findMany({orderBy:{number:'asc'}}),
  prisma.purchaseOrder.findMany({where:{OR:[{vehicleId:incident.vehicleId},{vehicleId:null},{id:incident.purchaseOrderId??''}]},orderBy:{number:'asc'}}),
  prisma.maintenance.findMany({where:{vehicleId:incident.vehicleId,OR:[{incidentId:null},{incidentId:id}]},orderBy:{scheduledAt:'desc'}}),
 ]);
 const order:Record<string,number>={CHECKLIST:0,DETECTED:1,CREATED:2,UPDATED:3,REFERENCES:4,MAINTENANCE:5,COMMENT:6,ATTACHMENT:7};
 const events=incident.events.sort((a,b)=>a.createdAt.getTime()-b.createdAt.getTime()||(order[a.kind]??9)-(order[b.kind]??9));
 return <div className="page operational-page incident-page"><Link className="subtle-link" href="/ocorrencias">← Todas as ocorrências</Link><div className="page-heading mt-5"><div className="min-w-0"><div className="eyebrow">{incident.publicNumber}</div><h1 className="break-words">{incident.title}</h1><p>{incident.vehicle.plate} · {incident.vehicle.model}</p></div><div className="flex flex-wrap gap-2"><StatusBadge status={incident.priority}/><IncidentStageBadge stage={incident.stage}/><a className="subtle-link" href="#atendimento">Registrar atendimento ↓</a></div></div>
 <RestrictionBanner status={incident.vehicle.operationalStatus}/><section className="mb-5 rounded-xl border border-slate-200 bg-white p-5"><dl className="grid gap-5 text-sm sm:grid-cols-2 xl:grid-cols-4">{[['Categoria',incidentCategories[incident.category]],['Origem',incidentOrigins[incident.origin]],['Abertura',incidentDate(incident.openedAt)],['Tempo aberto',`${openTime(incident.openedAt,incident.resolvedAt)}${incident.resolvedAt?' (até encerrar)':''}`],['Responsável',incident.responsible?.name??'Não atribuído'],['Prazo',incident.dueAt?incidentDate(incident.dueAt):'Não definido'],['Fornecedor',incident.supplier?.name??'Não definido'],['SC / Pedido',`${incident.requisition?.number??'Sem SC'} / ${incident.purchaseOrder?.orderNumber??'Sem pedido'}`]].map(([label,value])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>)}</dl><p className="mt-5 whitespace-pre-wrap break-words border-t border-slate-100 pt-4 text-sm text-slate-600">{incident.description}</p><div className="mt-4 flex flex-wrap gap-4 text-sm"><Link className="subtle-link" href={`/frota/${incident.vehicleId}`}>Consultar veículo</Link>{incident.purchaseOrderId?<Link className="subtle-link" href={`/compras/${incident.purchaseOrderId}`}>Abrir compra relacionada</Link>:<Link className="subtle-link" href={`/compras/nova?incident=${incident.id}`}>Solicitar compra</Link>}<Link className="subtle-link" href={`/manutencoes/nova?incident=${incident.id}`}>Solicitar manutenção</Link>{incident.checklistId&&<Link className="subtle-link" href={`/checklists/${incident.checklistId}`}>Checklist original</Link>}{incident.maintenance.map(m=><Link key={m.id} className="subtle-link min-w-0 max-w-full break-words" href={`/manutencoes/${m.id}`}>{m.serviceOrder??'Manutenção'} · {m.title}</Link>)}</div></section>
 <div className="grid min-w-0 items-start gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]"><div className="grid min-w-0 gap-5"><IncidentTimeline events={events}/>{incident.attachments.length>0&&<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Anexos preservados</h2><ul className="mt-3 space-y-3">{incident.attachments.map(a=><li key={a.id} className="min-w-0 text-sm"><a href={`/api/admin/incident-attachments/${a.id}`} className="subtle-link break-all">{a.fileName}</a><p className="mt-1 text-xs text-slate-500">{Math.ceil(a.sizeBytes/1024)} KB · {incidentDate(a.createdAt)} · {a.actor}</p></li>)}</ul></section>}</div>
 <IncidentEditor key={incident.revision} incident={{id,revision:incident.revision,stage:incident.stage,priority:incident.priority,responsibleId:incident.responsibleId,dueAt:incident.dueAt?.toISOString()??null,supplierId:incident.supplierId,requisitionId:incident.requisitionId,purchaseOrderId:incident.purchaseOrderId,solution:incident.solution,maintenanceIds:incident.maintenance.map(m=>m.id)}} options={{staff:staff.map(s=>({id:s.id,label:`${s.name} · ${s.employeeId}`})),suppliers:suppliers.map(s=>({id:s.id,label:s.tradeName??s.name})),requisitions:requisitions.map(s=>({id:s.id,label:s.number})),orders:orders.map(s=>({id:s.id,label:s.orderNumber??`Solicitação ${s.number.slice(0,12)}`})),maintenance:maintenance.map(s=>({id:s.id,label:`${s.serviceOrder??'Sem OS'} · ${s.title}`}))}}/></div>
 <VehicleRestrictions vehicleId={incident.vehicleId} incidentId={incident.id} showBanner={false}/>{incident.evaluation&&<ChecklistTrace evaluationId={incident.evaluation.id}/>}</div>;
}
