import {ModuleRefresh} from '@/components/module-refresh';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { FileText, ArrowUpRight, ShieldCheck, Database, QrCode } from 'lucide-react';
import { navigation } from '@/lib/navigation';
import { getModuleData } from '@/lib/module-data';
import { DataTable } from '@/components/data-table';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { prisma } from '@/lib/prisma';
import { currency } from '@/lib/utils';
export async function generateMetadata({ params }: { params: Promise<{ module: string }> }) { const { module } = await params; return { title: navigation.find(n => n.slug === module)?.label ?? 'Documentos' }; }
export default async function ModulePage({ params, searchParams }: { params: Promise<{ module: string }>; searchParams: Promise<{ record?: string }> }) {
  const { module } = await params; const title = module === 'documentos' ? 'Documentos' : navigation.find(n => n.slug === module)?.label;
  if (!title) notFound();
  if (module === 'configuracoes') return <div className="page"><div className="page-heading"><div><div className="eyebrow">GESTÃO</div><h1>Configurações</h1><p>Configuração inicial do ambiente e da operação.</p></div><Button asChild><Link href="/configuracoes/checklist">Configurar itens do checklist</Link></Button></div><div className="grid md:grid-cols-2 gap-5"><Card className="p-6"><ShieldCheck className="text-emerald-700 mb-4"/><h2 className="font-semibold">Bloqueios e liberações</h2><p className="text-sm text-slate-500 mt-3 mb-5">Estado inicial da restrição e evidências exigidas para liberação.</p><Button asChild variant="outline"><Link href="/configuracoes/restricoes">Configurar restrições</Link></Button></Card><Card className="p-6"><Database className="text-emerald-700 mb-4"/><h2 className="font-semibold">Ambiente de desenvolvimento</h2><dl className="mt-5 text-sm space-y-4"><div className="flex justify-between"><dt className="text-slate-500">Banco de dados</dt><dd>PostgreSQL / Prisma</dd></div><div className="flex justify-between"><dt className="text-slate-500">Fuso horário</dt><dd>America/Bahia</dd></div><div className="flex justify-between"><dt className="text-slate-500">Atualização do painel</dt><dd>A cada 30 segundos</dd></div></dl></Card><Card className="p-6"><ShieldCheck className="text-emerald-700 mb-4"/><h2 className="font-semibold">Acesso administrativo</h2><p className="text-sm text-slate-500 mt-3 leading-6">Acesso local para desenvolvimento. Autenticação e perfis de permissão serão necessários antes da implantação em produção.</p></Card><Card className="p-6"><QrCode className="text-emerald-700 mb-4"/><h2 className="font-semibold">Checklist por veículo</h2><p className="text-sm text-slate-500 mt-3 mb-5 leading-6">Cada veículo possui um link exclusivo. O motorista acessa apenas o formulário de inspeção, sem menus administrativos.</p><Button asChild variant="outline"><Link href="/frota">Acessar veículos<ArrowUpRight/></Link></Button></Card></div></div>;
  if (module === 'relatorios') {
    const [total, checks, costs, issues] = await Promise.all([prisma.vehicle.count(),prisma.checklist.count(),prisma.maintenance.aggregate({ _sum: { cost: true }, where: { status: 'COMPLETED' } }),prisma.incident.count({ where: { status: { in: ['OPEN','IN_PROGRESS'] } } })]);
    return <div className="page"><div className="page-heading"><div><div className="eyebrow">GESTÃO</div><h1>Relatórios</h1><p>Resumo dos registros e exportações da operação.</p><Link className="subtle-link mt-3" href="/indicadores">Abrir indicadores operacionais<ArrowUpRight size={14}/></Link></div></div><div className="metrics">{[['Veículos cadastrados',total],['Checklists registrados',checks],['Ocorrências abertas',issues],['Custo de serviços concluídos',currency(Number(costs._sum.cost ?? 0))]].map(([label,value]) => <Card className="p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-semibold mt-3">{value}</p></Card>)}</div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{[['frota','Inventário da frota'],['checklists','Histórico de inspeções'],['manutencoes','Custos e manutenções'],['ocorrencias','Pendências operacionais'],['documentos','Validade de documentos'],['compras','Pedidos de compras']].map(([slug,label]) => <Card className="p-6" key={slug}><FileText className="text-emerald-700 mb-4"/><h2 className="font-semibold">{label}</h2><p className="text-sm text-slate-500 mt-2 mb-5">Consulte, filtre e exporte os registros em CSV.</p><Link className="subtle-link" href={`/${slug}`}>Abrir relatório<ArrowUpRight size={14}/></Link></Card>)}</div></div>;
  }
  const data = await getModuleData(module); if (!data) notFound();
  const { record } = await searchParams;
  const rows = record ? data.rows.filter(row => row.id === record) : data.rows;
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">{['compras','fornecedores','motoristas'].includes(module) ? 'GESTÃO' : 'OPERAÇÃO'}</div><h1>{title}</h1><p>{data.description}</p></div>{module === 'frota' && <Button asChild variant="outline"><Link href="/documentos"><FileText/>Documentos</Link></Button>}</div>{record && <div className="flex items-center justify-between gap-3 mb-4 text-sm text-slate-500"><span>Registro selecionado pelo dashboard</span><Link href={`/${module}`} className="subtle-link">Mostrar todos os registros</Link></div>}{module==='alertas'&&<div className="mb-4"><ModuleRefresh/></div>}<DataTable key={record ?? 'all'} columns={data.columns} rows={rows} title={title}/></div>;
}
