import { PrismaClient } from '@prisma/client';
import { checklistItems, summarizeAnswers } from '../src/lib/checklist';

/** New, isolated fixtures. Empty updates deliberately preserve user edits and timestamps. */
export async function seedDataModel(db: PrismaClient) {
  const at = (days: number) => new Date(Date.now() + days * 86400000);
  await db.$transaction(async tx => {
    const costCenter = await tx.costCenter.upsert({ where: { code: 'DEMO-CC-001' }, update: {}, create: { code: 'DEMO-CC-001', name: 'Distribuição • demonstração' } });
    const staff = await tx.staffMember.upsert({ where: { employeeId: 'DEMO-FROTA-001' }, update: {}, create: { employeeId: 'DEMO-FROTA-001', name: 'Responsável de demonstração', email: 'frota@example.invalid' } });
    const driver = await tx.driver.upsert({ where: { employeeId: 'DEMO-M-001' }, update: {}, create: { name: 'Motorista de demonstração', employeeId: 'DEMO-M-001', phone: '(71) 0000-0000', license: 'DEMO-CNH-001', category: 'D', expiresAt: at(365), status: 'ACTIVE' } });
    const supplier = await tx.supplier.upsert({ where: { taxId: 'DEMO-CNPJ-002' }, update: {}, create: { name: 'Fornecedor Fictício de Peças Ltda.', tradeName: 'Peças Demonstração', taxId: 'DEMO-CNPJ-002', contactName: 'Contato de demonstração', phone: '(71) 0000-0000', email: 'pecas@example.invalid', specialty: 'Peças e elétrica', status: 'ACTIVE' } });
    const vehicle = await tx.vehicle.upsert({ where: { code: 'DEMO-FT-013' }, update: {}, create: { code: 'DEMO-FT-013', plate: 'DEM0A13', category: 'Caminhão', brand: 'Volkswagen', model: 'Delivery 11.180', year: 2024, unit: 'Demonstração', costCenterId: costCenter.id, mileage: 40500, status: 'AVAILABLE', availability: 'AVAILABLE', lastPreventiveAt: at(-30), nextPreventiveMileage: 50000, nextPreventiveAt: at(90), notes: 'Registro fictício para demonstrar o modelo ampliado.' } });
    const equipment = await tx.equipment.upsert({ where: { code: 'DEMO-EQ-001' }, update: {}, create: { code: 'DEMO-EQ-001', name: 'Compressor da oficina • demonstração', costCenterId: costCenter.id } });
    const requisition = await tx.purchaseRequisition.upsert({ where: { number: 'DEMO-SC-001' }, update: {}, create: { number: 'DEMO-SC-001', description: 'Reposição de lanterna traseira', requesterId: staff.id } });
    const purchase = await tx.purchaseOrder.upsert({ where: { number: 'DEMO-PC-001' }, update: {}, create: { number: 'DEMO-PC-001', requisitionId: requisition.id, description: 'Lanterna traseira completa', vehicleId: vehicle.id, supplierId: supplier.id, amount: 280, requesterId: staff.id, responsibleId: staff.id, requestedAt: at(-3), status: 'COMPLETED', notes: 'Pedido fictício concluído.' } });
    await tx.purchaseOrder.upsert({ where: { number: 'DEMO-PC-002' }, update: {}, create: { number: 'DEMO-PC-002', description: 'Filtro para compressor', equipmentId: equipment.id, supplierId: supplier.id, amount: 120, requesterId: staff.id, responsibleId: staff.id, status: 'OPEN', notes: 'Exemplo de pedido relacionado a equipamento.' } });
    const answers = checklistItems.map(item => ({ item: item.id, answer: item.id === 'lights' ? 'ISSUE' as const : 'OK' as const, category: item.category, priority: item.priority, generatesIncident: item.id === 'lights', notes: item.id === 'lights' ? 'Lanterna traseira danificada.' : '' }));
    const existingChecklist = await tx.checklist.findUnique({ where: { submissionKey: 'demo-v2-checklist' }, select: { id: true } });
    const checklist = await tx.checklist.upsert({ where: { submissionKey: 'demo-v2-checklist' }, update: {}, create: { submissionKey: 'demo-v2-checklist', vehicleId: vehicle.id, driverId: driver.id, driverName: driver.name, type: 'PRE_TRIP', status: 'REVIEWED', mileage: 40400, submittedAt: at(-4), latitude: -12.9714, longitude: -38.5014, locationAccuracy: 20, locationLabel: 'Localização fictícia • Salvador', ...summarizeAnswers(answers), notes: 'Inspeção fictícia com ocorrência resolvida.', answers: { create: answers } }, include: { answers: true } });
    const incident = await tx.incident.upsert({ where: { id: 'demo-v2-incident' }, update: {}, create: { id: 'demo-v2-incident', origin: 'CHECKLIST', vehicleId: vehicle.id, driverId: driver.id, checklistId: checklist.id, category: 'LIGHTING', title: 'Lanterna traseira danificada • demonstração', description: 'Identificada durante a inspeção antes da saída.', priority: 'HIGH', status: 'COMPLETED', openedAt: at(-4), dueAt: at(-2), responsibleId: staff.id, vehicleBlocked: false, resolvedAt: at(-1), solution: 'Lanterna substituída e funcionamento conferido.' } });
    const answer = checklist.answers.find(a => a.item === 'lights');
    // Only attach on first insertion of the fixture, not on subsequent seed runs.
    if (answer && !existingChecklist) {
      await tx.checklistAnswer.update({ where: { id: answer.id }, data: { incidentId: incident.id } });
    }
    await tx.maintenance.upsert({ where: { serviceOrder: 'DEMO-OS-001' }, update: {}, create: { serviceOrder: 'DEMO-OS-001', vehicleId: vehicle.id, supplierId: supplier.id, incidentId: incident.id, type: 'Corretiva', category: 'Elétrica', title: 'Troca de lanterna traseira', description: 'Substituição e teste do conjunto de iluminação.', requisitionId: requisition.id, purchaseOrderId: purchase.id, budget: 350, approvedAmount: 320, cost: 310, status: 'COMPLETED', scheduledAt: at(-3), enteredAt: at(-3), expectedAt: at(-1), completedAt: at(-1), mileage: 40400, responsibleId: staff.id } });
    if (answer) await tx.evidence.upsert({ where: { id: 'demo-v2-photo' }, update: {}, create: { id: 'demo-v2-photo', checklistAnswerId: answer.id, fileName: 'exemplo-foto-checklist.jpg', storageKey: 'demo/metadata-only/checklist.jpg', mimeType: 'image/jpeg', sizeBytes: 12000, description: 'Metadados fictícios de foto. Nenhum arquivo foi enviado.' } });
    await tx.evidence.upsert({ where: { id: 'demo-v2-evidence' }, update: {}, create: { id: 'demo-v2-evidence', incidentId: incident.id, fileName: 'exemplo-comprovante.pdf', storageKey: 'demo/metadata-only/solution.pdf', mimeType: 'application/pdf', sizeBytes: 24000, description: 'Metadados fictícios de evidência da solução, sem arquivo físico.' } });
  });
}
