import Link from 'next/link';
import {notFound} from 'next/navigation';
import {prisma} from '@/lib/prisma';
import {maintenanceKinds,maintenanceStages,closedMaintenance,elapsedLabel,maintenanceAlertState} from '@/lib/maintenance';
import {getMaintenanceOptions} from '@/lib/maintenance-options';
import {syncMaintenanceAlerts} from '@/lib/maintenance-alerts';
import {MaintenanceForm,type MaintenanceFormRecord} from '@/components/maintenance-form';
import {MaintenanceStageBadge} from '@/components/maintenance-stage';
import {RestrictionBanner} from '@/components/restriction-banner';
import {StatusBadge} from '@/components/status-badge';
import {currency} from '@/lib/utils';
import {incidentDate} from '@/lib/incidents';
export const dynamic='force-dynamic';
export default async function MaintenanceDetail({params}:{params:Promise<{id:string}>}){
 await syncMaintenanceAlerts();const {id}=await params;const m=await prisma.maintenance.findUnique({where:{id},include:{vehicle:true,responsible:true,supplier:true,incident:true,requisition:true,purchaseOrder:true,alert:true,events:{orderBy:{createdAt:'asc'}}}});if(!m)notFound();
 const alert=maintenanceAlertState(m);const record:MaintenanceFormRecord={id:m.id,revision:m.revision,submissionKey:m.submissionKey??undefined,vehicleId:m.vehicleId,kind:m.kind==='UNSPECIFIED'?undefined:m.kind,stage:m.stage,title:m.title,description:m.description,serviceOrder:m.serviceOrder,incidentId:m.incidentId,requisitionId:m.requisitionId,purchaseOrderId:m.purchaseOrderId,supplierId:m.supplierId,responsibleId:m.responsibleId,budget:m.budget===null?null:Number(m.budget),approvedAmount:m.approvedAmount===null?null:Number(m.approvedAmount),cost:m.costKnown?Number(m.cost):null,mileage:m.mileage,enteredAt:m.enteredAt?.toISOString()??null,scheduledAt:m.scheduledAt?.toISOString()??null,expectedAt:m.expectedAt?.toISOString()??null,unavailableFrom:m.unavailableFrom?.toISOString()??null,unavailableUntil:m.unavailableUntil?.toISOString()??null,completedAt:m.completedAt?.toISOString()??null,solution:m.solution,alertAfterHours:m.alertAfterHours,criticalAfterHours:m.criticalAfterHours};
 return <div className="page incident-page"><Link className="subtle-link" href="/manutencoes">← Manutenções</Link><div className="page-heading mt-5"><div className="min-w-0"><div className="eyebrow">{m.serviceOrder??'ORDEM DE SERVIÇO NÃO INFORMADA'}</div><h1 className="break-words">{m.title}</h1><p>{m.vehicle.plate} · {m.vehicle.model} · {maintenanceKinds[m.kind]}</p></div><MaintenanceStageBadge stage={m.stage}/></div><RestrictionBanner status={m.vehicle.operationalStatus}/>{alert&&<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><StatusBadge status={alert.priority}/><p className="mt-2 text-sm font-medium">{alert.reasons.join(' · ')}</p>{m.alert&&<Link className="subtle-link mt-2" href={`/alertas/${m.alert.id}`}>Ver alerta relacionado →</Link>}</div>}
 <section className="mb-5 rounded-xl border border-slate-200 bg-white p-5"><dl className="grid gap-5 text-sm sm:grid-cols-2 xl:grid-cols-4">{[['Tempo de indisponibilidade',elapsedLabel(m.unavailableFrom,m.unavailableUntil)],['Sem mudança de etapa',closedMaintenance(m.stage)?'Atendimento encerrado':elapsedLabel(m.stageChangedAt,null)],['Entrada',m.enteredAt?incidentDate(m.enteredAt):'Não informada'],['Previsão',m.expectedAt?incidentDate(m.expectedAt):'Não definida'],['Responsável',m.responsible?.name??'Não definido'],['Fornecedor',m.supplier?.name??'Não definido'],['SC / Pedido',`${m.requisition?.number??'Sem SC'} / ${m.purchaseOrder?.orderNumber??'Sem pedido'}`],['Valor realizado',m.costKnown?currency(Number(m.cost)):'Não informado'],['Orçamento',m.budget===null?'Não informado':currency(Number(m.budget))],['Valor aprovado',m.approvedAmount===null?'Não informado':currency(Number(m.approvedAmount))],['Indisponível desde',m.unavailableFrom?incidentDate(m.unavailableFrom):'Não registrado'],['Fim da indisponibilidade',m.unavailableUntil?incidentDate(m.unavailableUntil):m.unavailableFrom?'Em aberto':'Não registrado']].map(([label,value])=><div key={label} className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>)}</dl>{m.description&&<p className="mt-5 whitespace-pre-wrap break-words text-sm text-slate-600">{m.description}</p>}{m.solution&&<p className="mt-4 whitespace-pre-wrap break-words text-sm"><strong>Solução:</strong> {m.solution}</p>}<div className="mt-5 flex flex-wrap gap-5"><Link className="subtle-link" href={`/frota/${m.vehicleId}`}>Veículo e restrições operacionais</Link>{m.purchaseOrderId?<Link className="subtle-link" href={`/compras/${m.purchaseOrderId}`}>Abrir compra relacionada</Link>:<Link className="subtle-link" href={`/compras/nova?maintenance=${m.id}`}>Solicitar compra</Link>}{m.incident&&<Link className="subtle-link" href={`/ocorrencias/${m.incident.id}`}>{m.incident.publicNumber}</Link>}</div></section>
 <div className="grid min-w-0 items-start gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)]"><section className="min-w-0"><h2 className="mb-4 text-lg font-semibold">{closedMaintenance(m.stage)?'Serviço encerrado':'Registrar atendimento'}</h2>{closedMaintenance(m.stage)?<p className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Conclusão registrada em {m.completedAt?incidentDate(m.completedAt):'data não informada no cadastro anterior'}. O tempo desta manutenção foi encerrado quando havia indisponibilidade registrada. Restrições operacionais têm liberação própria. Para um novo serviço, faça outra solicitação.</p>:<MaintenanceForm key={m.revision} record={record} options={await getMaintenanceOptions()}/>}</section><section className="min-w-0 rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-5 text-lg font-semibold">Histórico da manutenção</h2><ol className="space-y-5 border-l-2 border-slate-100 pl-4">{m.events.map(e=>{const after=e.after&&typeof e.after==='object'&&!Array.isArray(e.after)?e.after:{};const stage=String(after.stage??'');return <li key={e.id}><p className="text-xs text-slate-500">{incidentDate(e.createdAt)}</p><p className="mt-1 text-sm font-semibold">{maintenanceStages[stage as keyof typeof maintenanceStages]??'Cadastro anterior'}</p><p className="mt-1 break-words text-xs text-slate-500">{e.actor}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{e.note}</p><details className="mt-2 text-xs text-slate-400"><summary className="cursor-pointer">Alterações preservadas</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({antes:e.before,depois:e.after},null,2)}</pre></details></li>;})}</ol></section></div></div>;
}
