import Link from 'next/link';
import {Prisma,IncidentStage,Priority} from '@prisma/client';
import {prisma} from '@/lib/prisma';
import {IncidentStageBadge} from '@/components/incident-stage';
import {StatusBadge} from '@/components/status-badge';
import {incidentStages,priorities,incidentCategories,incidentOrigins,incidentDate,openTime} from '@/lib/incidents';
import {Button} from '@/components/ui/button';
export const dynamic='force-dynamic';
export default async function IncidentsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams;const value=(key:string)=>typeof params[key]==='string'?params[key] as string:'';
 const q=value('q').trim().slice(0,100),stage=value('stage'),priority=value('priority'),record=value('record');
 const page=Math.max(1,Math.min(100000,Number(value('page'))||1));
 const where:Prisma.IncidentWhereInput={...(record?{id:record}:{}),...(Object.hasOwn(incidentStages,stage)?{stage:stage as IncidentStage}:{}),...(Object.hasOwn(priorities,priority)?{priority:priority as Priority}:{}),...(q?{OR:[{publicNumber:{contains:q,mode:'insensitive'}},{title:{contains:q,mode:'insensitive'}},{vehicle:{plate:{contains:q,mode:'insensitive'}}},{responsible:{name:{contains:q,mode:'insensitive'}}}]}:{})};
 const [total,incidents]=await prisma.$transaction([prisma.incident.count({where}),prisma.incident.findMany({where,include:{vehicle:true,responsible:true},orderBy:[{priority:'desc'},{openedAt:'asc'}],take:20,skip:(Math.floor(page)-1)*20})]);
 const href=(next:number)=>{const p=new URLSearchParams({q,stage,priority,page:String(next)});if(record)p.set('record',record);return `/ocorrencias?${p}`;};
 return <div className="page operational-page"><div className="page-heading"><div><div className="eyebrow">ATENDIMENTO OPERACIONAL</div><h1>Ocorrências</h1><p>Da identificação do problema à solução, com histórico de cada atendimento.</p></div><span className="badge badge-blue">{total} registro{total!==1?'s':''}</span></div>
 <form className="mb-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_auto_auto]" action="/ocorrencias">
 <label className="text-xs font-medium text-slate-600">Buscar<input className="field mt-1 w-full" name="q" defaultValue={q} placeholder="Número, placa, problema ou responsável"/></label>
 <label className="text-xs font-medium text-slate-600">Status<select className="field mt-1 w-full" name="stage" defaultValue={stage}><option value="">Todos</option>{Object.entries(incidentStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label className="text-xs font-medium text-slate-600">Criticidade<select className="field mt-1 w-full" name="priority" defaultValue={priority}><option value="">Todas</option>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {record&&<input type="hidden" name="record" value={record}/>}<Button className="self-end" type="submit">Filtrar</Button><Button className="self-end" variant="outline" asChild><Link href="/ocorrencias">Limpar</Link></Button></form>
 <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="op-section-heading"><div><h2>FILA DE OCORRÊNCIAS</h2><p>Críticas primeiro; dentro de cada prioridade, as mais antigas.</p></div></div><div className="op-table-scroll" role="region" aria-label="Tabela de ocorrências" tabIndex={0}><table className="op-table incidents-table" style={{minWidth:1500}}><thead><tr>{['Número','Criticidade','Placa','Problema','Categoria','Origem','Abertura','Tempo aberto','Responsável','Status','Prazo','Ações'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{incidents.map(i=><tr key={i.id}><td className="whitespace-nowrap font-semibold"><Link className="subtle-link" href={`/ocorrencias/${i.id}`}>{i.publicNumber}</Link></td><td><StatusBadge status={i.priority}/></td><td className="whitespace-nowrap">{i.vehicle.plate}</td><td className="op-problem">{i.title}</td><td>{incidentCategories[i.category]}</td><td>{incidentOrigins[i.origin]}</td><td className="op-detected">{incidentDate(i.openedAt)}</td><td className="op-age">{openTime(i.openedAt,i.resolvedAt)}{i.resolvedAt&&<small className="block">Até o encerramento</small>}</td><td>{i.responsible?.name??<span className="op-unassigned">Não atribuído</span>}</td><td><IncidentStageBadge stage={i.stage}/></td><td className="whitespace-nowrap">{i.dueAt?<span className={!i.resolvedAt&&i.dueAt<new Date()?'font-semibold text-red-700':''}>{incidentDate(i.dueAt)}</span>:'Não definido'}</td><td><Link className="op-row-action" href={`/ocorrencias/${i.id}`}>Atender →</Link></td></tr>)}</tbody></table></div>{!incidents.length&&<div className="op-empty">{total?'Esta página não possui registros. Volte para a página anterior.':q||stage||priority||record?'Nenhuma ocorrência corresponde aos filtros.':'Nenhuma ocorrência registrada. Problemas dos checklists aparecerão aqui conforme as regras configuradas.'}</div>}<div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-4 text-xs text-slate-500"><span>Página {Math.floor(page)} · {total} registros</span><div className="flex gap-3">{page>1&&<Link className="subtle-link" href={href(page-1)}>← Anterior</Link>}{page*20<total&&<Link className="subtle-link" href={href(page+1)}>Próxima →</Link>}</div></div></section></div>;
}
