'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {alertStages,type AlertStageKey} from '@/lib/alerts';
import {Button} from './ui/button';
export function AlertForm({alert,staff}:{alert:{id:string;revision:number;stage:AlertStageKey;responsibleId:string|null;actionRequired:string};staff:{id:string;name:string;employeeId:string;active:boolean}[]}){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[newStaff,setNewStaff]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const data=new FormData(e.currentTarget),value=(key:string)=>String(data.get(key)??'');try{const response=await fetch(`/api/admin/alerts/${alert.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:alert.revision,stage:value('stage'),responsibleId:newStaff?null:value('responsibleId')||null,...(newStaff?{newResponsible:{name:value('responsibleName'),employeeId:value('responsibleEmployeeId')}}:{}),actionRequired:value('actionRequired'),note:value('note'),operatorName:value('operatorName'),operatorId:value('operatorId')})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage('Atendimento registrado no histórico.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Falha de conexão.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Registrar atendimento</h2><p className="mt-2 text-xs text-slate-500">Resolver, tratar ou classificar como não procedente retira o alerta da fila principal. O histórico permanece disponível. O atendimento do alerta não libera o veículo nem encerra o serviço de origem.</p><fieldset disabled={busy} className="mt-5 grid min-w-0 gap-4 sm:grid-cols-2"><label className="grid min-w-0 gap-1 text-sm">Status do alerta<select aria-label="Status do alerta" name="stage" className="field min-w-0" defaultValue={alert.stage}>{Object.entries(alertStages).filter(([k])=>k!=='RULE_CLOSED'||alert.stage==='RULE_CLOSED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="grid min-w-0 gap-1 text-sm">Responsável<select aria-label="Responsável" name="responsibleId" className="field min-w-0" disabled={newStaff||busy} defaultValue={alert.responsibleId??''}><option value="">Não atribuído</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.employeeId}{!s.active?' (inativo)':''}</option>)}</select></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={newStaff} onChange={e=>setNewStaff(e.target.checked)}/>Cadastrar responsável</label>{newStaff&&<><label className="grid min-w-0 gap-1 text-sm">Nome do responsável<input name="responsibleName" className="field min-w-0" required minLength={3} maxLength={100}/></label><label className="grid min-w-0 gap-1 text-sm">Matrícula do responsável<input name="responsibleEmployeeId" className="field min-w-0" required maxLength={60}/></label></>}<label className="grid min-w-0 gap-1 text-sm sm:col-span-2">Ação necessária<textarea name="actionRequired" className="field min-w-0" required minLength={3} maxLength={1000} rows={2} defaultValue={alert.actionRequired}/></label><label className="grid min-w-0 gap-1 text-sm sm:col-span-2">Atendimento / motivo<textarea name="note" className="field min-w-0" required minLength={5} maxLength={3000} rows={3} placeholder="Providência, solução, justificativa ou motivo da reabertura"/></label><label className="grid min-w-0 gap-1 text-sm">Seu nome<input name="operatorName" className="field min-w-0" required minLength={3} maxLength={100}/></label><label className="grid min-w-0 gap-1 text-sm">Sua matrícula / identificação<input name="operatorId" className="field min-w-0" required maxLength={60}/></label><p className="text-xs text-slate-500 sm:col-span-2">Identificação autodeclarada no ambiente administrativo local.</p><Button type="submit">{busy?'Salvando…':'Salvar atendimento'}</Button></fieldset>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}</form>;
}
