import Link from 'next/link';
import {prisma} from '@/lib/prisma';
import {PriorityBadge} from '@/components/operational-table';
import {labels} from '@/components/status-badge';
export async function ChecklistTrace({evaluationId}:{evaluationId:string}){
 const e=await prisma.checklistEvaluation.findUniqueOrThrow({where:{id:evaluationId},include:{answer:{include:{checklist:{include:{vehicle:true}},photos:{select:{id:true}}}},incident:true,alert:true}});
 const a=e.answer;
 return <section className="rounded-xl border border-slate-200 bg-white p-6 mt-5"><div className="flex justify-between flex-wrap gap-3"><h2 className="font-semibold text-lg">Rastreabilidade do checklist</h2><PriorityBadge priority={e.priority}/></div><p className="text-sm text-slate-500 mt-2">Resposta original preservada. As regras abaixo são as utilizadas no envio.</p><dl className="grid sm:grid-cols-2 gap-5 text-sm mt-6">{[
 ['Veículo',`${a.checklist.vehicle.plate} · ${a.checklist.vehicle.model}`],['Motorista / identificação',a.checklist.driverIdentification??a.checklist.driverName],['Item',`${a.categoryLabel} · ${a.itemLabel}`],['Resposta original',a.answer==='ISSUE'?'PROBLEMA':a.answer],['Tipo de problema',a.problemType??'Não informado'],['Observação',a.notes||'Não informada'],['Avaliado em',e.evaluatedAt.toLocaleString('pt-BR',{timeZone:'America/Bahia'})],['Gerar ocorrência',e.createsIncident?'Sim':'Não'],['Bloquear veículo',e.blocksVehicle?'Sim':'Não'],['Situação antes do processamento',`${labels[e.vehicleStatusBefore]??e.vehicleStatusBefore} · ${e.availabilityBefore==='AVAILABLE'?'Disponível':e.availabilityBefore==='UNAVAILABLE'?'Indisponível':'Disponibilidade não informada'}`],['Situação após o processamento',`${labels[e.vehicleStatusAfter]??e.vehicleStatusAfter} · ${e.availabilityAfter==='AVAILABLE'?'Disponível':e.availabilityAfter==='UNAVAILABLE'?'Indisponível':'Disponibilidade não informada'}`],['Fotos preservadas',String(a.photos.length)],
 ].map(([label,value])=><div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words font-medium">{value}</dd></div>)}</dl><div className="flex flex-wrap gap-5 mt-6 text-sm"><Link className="subtle-link" href={`/checklists/${a.checklistId}`}>Ver checklist e evidências</Link>{e.incident&&<Link className="subtle-link" href={`/ocorrencias/${e.incident.id}`}>Ocorrência {e.incident.publicNumber}</Link>}{e.alert&&<Link className="subtle-link" href={`/alertas/${e.alert.id}`}>Ver alerta relacionado</Link>}</div><details className="mt-6 text-xs text-slate-500"><summary className="cursor-pointer">Registro técnico da regra aplicada</summary><p className="mt-3 break-all">Avaliação {e.id} · Resposta {e.answerId} · Motor {e.engineVersion} · Configuração {e.configVersion}</p><pre className="mt-3 overflow-auto whitespace-pre-wrap break-words">{JSON.stringify(e.ruleSnapshot,null,2)}</pre></details></section>;
}
