'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {z} from 'zod';
import {configItemSchema} from '@/lib/checklist-config-validation';
import {StatusBadge} from './status-badge';
import {PriorityBadge} from './operational-table';
import {Button} from './ui/button';
import {Card} from './ui/card';
type Item=z.infer<typeof configItemSchema> & {id:string;updatedAt:string};
export function ChecklistConfigurator({categories,types,items}:{categories:{id:string;name:string}[];types:string[];items:Item[]}){
 const router=useRouter();const formRef=useRef<HTMLFormElement>(null);
 const blank=():z.infer<typeof configItemSchema>=>({categoryId:categories[0]?.id??'',label:'',help:'',problems:['Outro'],priority:'MEDIUM',requiresPhoto:true,generatesIncident:true,blocksVehicle:false,allowsNotApplicable:false,vehicleTypes:[],active:true,sortOrder:0});
 const [form,setForm]=useState(blank);const [options,setOptions]=useState('Outro');const [allTypes,setAllTypes]=useState(true);
 const [search,setSearch]=useState('');const [categoryFilter,setCategoryFilter]=useState('');const [typeFilter,setTypeFilter]=useState('');const [status,setStatus]=useState('active');
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const set=<K extends keyof typeof form>(key:K,value:typeof form[K])=>setForm(f=>({...f,[key]:value}));
 function edit(item?:Item){setForm(item??blank());setOptions(item?.problems.join('\n')??'Outro');setAllTypes(!item?.vehicleTypes.length);setError('');formRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function save(data:z.infer<typeof configItemSchema>){
  if(busy)return;setBusy(true);setError('');setNotice('');
  try{const response=await fetch('/api/admin/checklist-items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw new Error(body.error??'Não foi possível salvar.');setNotice('Configuração salva. As próximas inspeções usarão estas regras.');setForm(blank());setOptions('Outro');setAllTypes(true);router.refresh();}
  catch(e){setError(e instanceof TypeError?'Sem conexão. Verifique a internet e tente novamente.':e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}
 }
 function submit(e:React.FormEvent){e.preventDefault();if(!allTypes&&!form.vehicleTypes.length){setError('Selecione ao menos um tipo ou marque todos os tipos.');return;}const parsed=configItemSchema.safeParse({...form,vehicleTypes:allTypes?[]:form.vehicleTypes,problems:options.split('\n').map(p=>p.trim()).filter(Boolean)});if(!parsed.success){setError(parsed.error.issues[0]?.message??'Confira os campos.');return;}void save(parsed.data);}
 const visible=items.filter(i=>(!search||i.label.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))&&(!categoryFilter||i.categoryId===categoryFilter)&&(!typeFilter||!i.vehicleTypes.length||i.vehicleTypes.includes(typeFilter))&&(status==='all'||i.active===(status==='active')));
 return <><p className="mb-5 rounded-lg bg-blue-50 p-4 text-sm text-blue-900">As regras de foto, ocorrência e bloqueio são aplicadas quando há PROBLEMA. As inspeções enviadas preservam os nomes e as regras vigentes no momento do envio.</p>{error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-lg bg-green-50 p-4 text-green-800">{notice}</p>}
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px] items-start"><section className="min-w-0"><Card className="p-4 mb-4"><div className="flex flex-wrap gap-3"><input className="field flex-1 min-w-40" aria-label="Buscar item" placeholder="Buscar item…" value={search} onChange={e=>setSearch(e.target.value)}/><select className="field" aria-label="Filtrar categoria" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="field" aria-label="Filtrar tipo de veículo" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Todos os tipos</option>{types.map(t=><option key={t}>{t}</option>)}</select><select className="field" aria-label="Filtrar atividade" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select></div><p className="text-xs text-slate-500 mt-3">{visible.length} itens · {categories.length} categorias · aplicação por perfil do veículo, ou categoria quando não há perfil.</p></Card>
 <div className="space-y-3">{visible.map(item=><Card key={item.id} className="p-4"><div className="flex justify-between gap-3 flex-wrap"><div><p className="text-xs text-slate-500 mb-1">{categories.find(c=>c.id===item.categoryId)?.name} · Ordem {item.sortOrder}</p><h2 className="font-semibold">{item.label}</h2></div><div className="flex items-center gap-2"><PriorityBadge priority={item.priority}/>{!item.active&&<StatusBadge status="INACTIVE"/>}</div></div><p className="text-sm text-slate-500 mt-2">{item.vehicleTypes.length?item.vehicleTypes.join(' · '):'Todos os tipos de veículos'}</p><p className="text-xs text-slate-600 mt-3">Foto {item.requiresPhoto?'obrigatória':'opcional'} · {item.generatesIncident?'Gera ocorrência':'Sem ocorrência automática'} · {item.blocksVehicle?'Bloqueia veículo':'Não bloqueia'}{item.allowsNotApplicable?' · Permite não se aplica':''}</p><div className="flex gap-2 mt-3"><Button variant="outline" disabled={busy} onClick={()=>edit(item)} aria-label={`Editar ${item.label}`}>Editar</Button><Button variant="ghost" disabled={busy} onClick={()=>void save({...item,active:!item.active})} aria-label={`${item.active?'Desativar':'Ativar'} ${item.label}`}>{item.active?'Desativar':'Ativar'}</Button></div></Card>)}{!visible.length&&<Card className="p-8 text-center text-slate-500">Nenhum item corresponde aos filtros.</Card>}</div></section>
 <Card className="p-5 order-first xl:order-last"><form ref={formRef} onSubmit={submit} className="scroll-mt-5"><div className="flex justify-between items-center mb-5"><h2 className="font-semibold text-lg">{form.id?'Editar item':'Criar item'}</h2>{form.id&&<Button type="button" variant="ghost" onClick={()=>edit()} disabled={busy}>Novo item</Button>}</div><fieldset disabled={busy} className="space-y-4 min-w-0">
 <label className="block text-sm">Categoria<select className="field w-full mt-1" aria-label="Categoria do item" value={form.categoryId} onChange={e=>set('categoryId',e.target.value)} required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label className="block text-sm">Nome do item<input className="field w-full mt-1" value={form.label} onChange={e=>set('label',e.target.value)} minLength={2} maxLength={120} required/></label>
 <label className="block text-sm">Orientação ao motorista<textarea className="field w-full mt-1" rows={2} value={form.help} onChange={e=>set('help',e.target.value)} maxLength={300}/></label>
 <div className="grid grid-cols-2 gap-3"><label className="block text-sm">Criticidade<select className="field w-full mt-1" aria-label="Criticidade" value={form.priority} onChange={e=>set('priority',e.target.value as Item['priority'])}><option value="LOW">Normal</option><option value="MEDIUM">Atenção</option><option value="HIGH">Urgente</option><option value="CRITICAL">Crítico</option></select></label><label className="block text-sm">Ordem na categoria<input className="field w-full mt-1" type="number" min={0} max={9999} value={form.sortOrder} onChange={e=>set('sortOrder',Number(e.target.value))} required/></label></div>
 <label className="block text-sm">Tipos de problema (um por linha)<textarea className="field w-full mt-1" rows={4} value={options} onChange={e=>setOptions(e.target.value)} required/><span className="text-xs text-slate-500">De 1 a 20 opções. O motorista não precisa digitar uma descrição.</span></label>
 <fieldset className="rounded-lg border border-slate-200 p-3 space-y-3"><legend className="text-sm px-1">Quando houver problema</legend>{([['requiresPhoto','Exige foto'],['generatesIncident','Gera ocorrência'],['blocksVehicle','Bloqueia veículo']] as const).map(([key,label])=><label key={key} className="flex gap-3 items-center text-sm min-h-8"><input type="checkbox" checked={form[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>)}</fieldset>
 <label className="flex gap-3 items-center text-sm"><input type="checkbox" checked={form.allowsNotApplicable} onChange={e=>set('allowsNotApplicable',e.target.checked)}/>Permitir resposta “Não se aplica”</label>
 <fieldset className="rounded-lg border border-slate-200 p-3 space-y-3"><legend className="text-sm px-1">Tipos / perfis de veículos</legend><label className="flex gap-3 text-sm items-center"><input type="checkbox" checked={allTypes} onChange={e=>setAllTypes(e.target.checked)}/>Todos os tipos, inclusive novos</label>{!allTypes&&types.map(t=><label key={t} className="flex gap-3 text-sm items-center min-h-8"><input type="checkbox" checked={form.vehicleTypes.includes(t)} onChange={e=>set('vehicleTypes',e.target.checked?[...form.vehicleTypes,t]:form.vehicleTypes.filter(v=>v!==t))}/>{t}</label>)}</fieldset>
 <label className="flex gap-3 items-center text-sm"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/>Item ativo</label><Button type="submit" className="w-full">{busy?'Salvando…':'Salvar item'}</Button>
 </fieldset></form></Card></div></>;
}
