'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Search, ChevronLeft, ChevronRight, ArrowUpDown, Download, ArrowUpRight } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { StatusBadge, labels } from '@/components/status-badge';
export type DataRow = { id: string; cells: string[]; status: string; href?: string };
export function DataTable({ columns, rows, title }: { columns: string[]; rows: DataRow[]; title: string }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(0); const [sort, setSort] = useState<{ col: number; asc: boolean } | null>(null);
  const filtered = useMemo(() => rows.filter(r => (!status || r.status === status) && `${r.cells.join(' ')} ${labels[r.status] ?? r.status}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).sort((a,b) => sort ? a.cells[sort.col].localeCompare(b.cells[sort.col], 'pt-BR', { numeric: true })*(sort.asc ? 1 : -1) : 0), [rows, query, status, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length/10)); const currentPage = Math.min(page, pages-1);
  const exportCsv = () => {
    const safe = (s: string) => `"${(/^[=+@\-\t\r]/.test(s) ? "'" : '') + s.replaceAll('"', '""')}"`;
    const csv = '\uFEFF' + [[...columns,'Status'],...filtered.map(r => [...r.cells,labels[r.status] ?? r.status])].map(row => row.map(safe).join(';')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = `${title.toLowerCase().replaceAll(' ','-')}.csv`; a.click(); URL.revokeObjectURL(url);
  };
  return <Card><div className="p-5 flex flex-wrap gap-3 items-center"><div className="relative flex-1 min-w-48"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="field w-full pl-10!" placeholder={`Buscar em ${title.toLowerCase()}…`} aria-label={`Buscar em ${title}`} value={query} onChange={e => { setQuery(e.target.value); setPage(0); }}/></div><select className="field" aria-label="Filtrar status" value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}><option value="">Todos os status</option>{Array.from(new Set(rows.map(r => r.status))).map(s => <option key={s} value={s}>{labels[s] ?? s}</option>)}</select><Button variant="outline" onClick={exportCsv}><Download/>Exportar CSV</Button></div><Table><TableHeader><TableRow>{columns.map((c,i) => <TableHead key={c} aria-sort={sort?.col === i ? (sort.asc ? 'ascending' : 'descending') : 'none'}><button className="inline-flex items-center gap-2" onClick={() => setSort({ col: i, asc: sort?.col === i ? !sort.asc : true })}>{c}<ArrowUpDown size={12}/></button></TableHead>)}<TableHead>Status</TableHead>{rows.some(r => r.href) && <TableHead>Detalhes</TableHead>}</TableRow></TableHeader><TableBody>{filtered.slice(currentPage*10,currentPage*10+10).map(r => <TableRow key={r.id}>{r.cells.map((c,i) => <TableCell className={i === 0 ? 'font-medium' : ''} key={i}>{c}</TableCell>)}<TableCell><StatusBadge status={r.status}/></TableCell>{rows.some(row => row.href) && <TableCell>{r.href && <Link href={r.href} aria-label={`Detalhes de ${r.cells[0]}`} className="subtle-link">Abrir<ArrowUpRight size={14}/></Link>}</TableCell>}</TableRow>)}</TableBody></Table>{!filtered.length && <div className="empty-state"><Search className="mx-auto mb-3 text-slate-300" size={30}/><h3>Nenhum registro encontrado</h3><p>Experimente outra busca ou altere os filtros.</p>{(query || status) && <Button className="mt-4" variant="outline" onClick={() => { setQuery(''); setStatus(''); }}>Limpar filtros</Button>}</div>}<div className="px-5 py-4 border-t border-slate-100 flex items-center justify-between gap-3 text-xs text-slate-500"><span>{filtered.length} registros · Página {currentPage+1} de {pages}</span><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="Página anterior" disabled={currentPage === 0} onClick={() => setPage(currentPage-1)}><ChevronLeft/></Button><Button size="icon" variant="ghost" aria-label="Próxima página" disabled={currentPage+1 >= pages} onClick={() => setPage(currentPage+1)}><ChevronRight/></Button></div></div></Card>;
}
