'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button} from '@/components/ui/button';
import {incidentStages,priorities,closedStages} from '@/lib/incidents';
type Option={id:string;label:string};
export type IncidentEditorProps={incident:{id:string;revision:number;stage:keyof typeof incidentStages;priority:keyof typeof priorities;responsibleId:string|null;dueAt:string|null;supplierId:string|null;requisitionId:string|null;purchaseOrderId:string|null;solution:string|null;maintenanceIds:string[]};options:{staff:Option[];suppliers:Option[];requisitions:Option[];orders:Option[];maintenance:Option[]}};
function localDate(value:string|null){return value?new Date(new Date(value).getTime()-3*3600000).toISOString().slice(0,16):'';}
export function IncidentEditor({incident,options}:IncidentEditorProps){
 const router=useRouter();const [stage,setStage]=useState(incident.stage),[priority,setPriority]=useState(incident.priority),[newStaff,setNewStaff]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState(false);
 async function save(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();setBusy(true);setSuccess(false);setMessage('');const form=event.currentTarget;const fields=new FormData(form);const text=(name:string)=>String(fields.get(name)??'');
  try{
   let attachment;const file=fields.get('attachment');
   if(file instanceof File&&file.size){
    if(file.size>5*1024*1024)throw new Error('O anexo deve ter até 5 MB.');
    const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Não foi possível ler o anexo.'));reader.readAsDataURL(file);});
    attachment={fileName:file.name,mimeType:file.type,base64};
   }
   const response=await fetch(`/api/admin/incidents/${incident.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:incident.revision,operatorName:text('operatorName'),operatorId:text('operatorId'),stage,priority,justification:text('justification'),responsibleId:newStaff?null:text('responsibleId')||null,...(newStaff?{newResponsible:{name:text('responsibleName'),employeeId:text('responsibleEmployeeId')}}:{}),dueAt:text('dueAt')===localDate(incident.dueAt)?incident.dueAt:text('dueAt')?new Date(`${text('dueAt')}:00-03:00`).toISOString():null,supplierId:text('supplierId')||null,requisitionId:text('requisitionId')||null,purchaseOrderId:text('purchaseOrderId')||null,maintenanceIds:fields.getAll('maintenanceIds'),solution:text('solution'),comment:text('comment'),attachment})});
   const result=await response.json();if(!response.ok)throw new Error(result.error??'Não foi possível salvar.');
   setSuccess(true);setMessage('Atendimento registrado no histórico.');router.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar. Confira a conexão e tente novamente.');}finally{setBusy(false);}
 }
 const select=(name:string,label:string,list:Option[],value:string|null)=><label className="grid gap-1 text-sm text-slate-600">{label}<select name={name} className="field w-full min-w-0" defaultValue={value??''}><option value="">Não definido</option>{list.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>{list.length===0&&<small className="text-xs text-slate-400">Nenhum cadastro disponível.</small>}</label>;
 return <section id="atendimento" className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Registrar atendimento</h2><p className="mt-1 text-sm text-slate-500">As alterações são acrescentadas à timeline. O histórico anterior é preservado.</p><form onSubmit={save} className="mt-5"><fieldset disabled={busy||success} className="grid min-w-0 gap-5 disabled:opacity-70">
 <div className="rounded-lg border border-blue-100 bg-blue-50 p-3"><p className="mb-3 text-xs text-blue-900">Ambiente local: informe quem está realizando o atendimento. Esta identificação é autodeclarada; ainda não existe autenticação de usuários.</p><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Seu nome<input required name="operatorName" minLength={3} maxLength={100} autoComplete="name" className="field w-full"/></label><label className="grid gap-1 text-sm">Sua matrícula / identificação<input required name="operatorId" maxLength={60} className="field w-full"/></label></div></div>
 <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Status<select className="field w-full" value={stage} onChange={e=>setStage(e.target.value as typeof stage)}>{Object.entries(incidentStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="grid gap-1 text-sm">Criticidade<select className="field w-full" value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 <label className="grid gap-1 text-sm">Justificativa {priority!==incident.priority||closedStages.includes(incident.stage)&&!closedStages.includes(stage)?'(obrigatória)':'(opcional)'}<textarea name="justification" rows={2} maxLength={2000} required={priority!==incident.priority||closedStages.includes(incident.stage)&&!closedStages.includes(stage)} minLength={5} className="field w-full" placeholder="Explique a mudança de criticidade ou a reabertura."/></label>
 <div>{!newStaff&&select('responsibleId','Responsável',options.staff,incident.responsibleId)}<label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={newStaff} onChange={e=>setNewStaff(e.target.checked)}/>Cadastrar responsável</label>{newStaff&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Nome do responsável<input required minLength={3} maxLength={100} name="responsibleName" className="field w-full"/></label><label className="grid gap-1 text-sm">Matrícula do responsável<input required maxLength={60} name="responsibleEmployeeId" className="field w-full"/></label></div>}</div>
 <label className="grid gap-1 text-sm">Prazo (horário de Brasília)<input type="datetime-local" name="dueAt" defaultValue={localDate(incident.dueAt)} className="field w-full min-w-0"/></label>
 <details className="rounded-lg border border-slate-200 p-3" open><summary className="cursor-pointer text-sm font-semibold">Manutenção e compras</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{select('supplierId','Fornecedor',options.suppliers,incident.supplierId)}{select('requisitionId','SC',options.requisitions,incident.requisitionId)}{select('purchaseOrderId','Pedido',options.orders,incident.purchaseOrderId)}</div><fieldset className="mt-4"><legend className="text-sm text-slate-600">Manutenções deste veículo</legend>{options.maintenance.length?options.maintenance.map(m=><label key={m.id} className="mt-2 flex items-start gap-2 text-sm"><input className="mt-1" name="maintenanceIds" type="checkbox" value={m.id} defaultChecked={incident.maintenanceIds.includes(m.id)}/>{m.label}</label>):<p className="mt-2 text-xs text-slate-400">Nenhuma manutenção disponível para vincular.</p>}</fieldset></details>
 <label className="grid gap-1 text-sm">Solução / motivo do encerramento {closedStages.includes(stage)?'(obrigatório)':'(opcional)'}<textarea name="solution" rows={3} maxLength={5000} required={closedStages.includes(stage)} minLength={5} defaultValue={incident.solution??''} className="field w-full"/></label>
 <label className="grid gap-1 text-sm">Adicionar comentário<textarea name="comment" rows={3} maxLength={5000} className="field w-full" placeholder="Registre o andamento do atendimento."/></label>
 <label className="grid gap-1 text-sm">Anexar foto ou documento<input name="attachment" type="file" accept="image/jpeg,image/png,application/pdf" className="field w-full min-w-0 text-xs"/><small className="text-xs text-slate-500">JPEG, PNG ou PDF · até 5 MB por atendimento.</small></label>
 <p className="rounded-lg bg-amber-50 p-3 text-xs leading-relaxed text-amber-900">Liberar ou concluir esta ocorrência encerra seu alerta. A disponibilidade do veículo precisa ser verificada na Frota: o encerramento não remove bloqueios nem libera o veículo automaticamente.</p>
 <Button type="submit" className="w-full">{busy?'Registrando…':closedStages.includes(stage)&&stage!==incident.stage?'Encerrar e registrar atendimento':'Salvar atendimento'}</Button></fieldset>{message&&<p role={success?'status':'alert'} className={`mt-4 text-sm ${success?'text-emerald-700':'text-red-700'}`}>{message}</p>}</form></section>;
}
