import type {IncidentEvent,Prisma} from '@prisma/client';
import {incidentDate,incidentStages,priorities} from '@/lib/incidents';
const titles:Record<string,string>={PURCHASE:'Atendimento de compras',RESTRICTION:'Restrição operacional',CHECKLIST:'Checklist realizado',DETECTED:'Problema identificado',CREATED:'Ocorrência criada',UPDATED:'Atendimento registrado',COMMENT:'Comentário adicionado',ATTACHMENT:'Anexo adicionado',MAINTENANCE_SERVICE:'Atendimento de manutenção',MAINTENANCE:'Manutenção relacionada',REFERENCES:'Vínculos do atendimento',MIGRATED:'Histórico iniciado'};
const fields:Record<string,string>={stage:'Status',priority:'Criticidade',responsibleId:'Responsável',dueAt:'Prazo',supplierId:'Fornecedor',requisitionId:'SC',purchaseOrderId:'Pedido',solution:'Solução',resolvedAt:'Encerramento'};
const object=(value:Prisma.JsonValue|null):Prisma.JsonObject=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
function display(key:string,value:Prisma.JsonValue|undefined){
 if(value===null||value===undefined||value==='')return 'Não definido';
 const str=String(value);
 if(key.endsWith('Id'))return 'Vinculado (identificação no atendimento)';
 if(key==='stage')return incidentStages[str as keyof typeof incidentStages]??str;
 if(key==='priority')return priorities[str as keyof typeof priorities]??str;
 if(key==='dueAt'||key==='resolvedAt')return incidentDate(str.endsWith('Z')?str:`${str}Z`);
 return str;
}
export function IncidentTimeline({events}:{events:IncidentEvent[]}){
 return <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-6 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Timeline da ocorrência</h2><span className="text-xs text-slate-500">Horário de Brasília</span></div>{events.length===0?<p className="text-sm text-slate-500">Nenhum evento registrado.</p>:<ol className="ml-2 border-l-2 border-slate-100">{events.map(e=>{const before=object(e.before),after=object(e.after);const changes=Object.keys(fields).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));return <li key={e.id} className="relative pb-7 pl-6 last:pb-0"><span className="absolute -left-[6px] top-1.5 size-2.5 rounded-full bg-emerald-600 ring-4 ring-white"/><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-sm font-semibold">{titles[e.kind]??e.kind}</h3><time dateTime={e.createdAt.toISOString()} className="text-xs text-slate-500">{incidentDate(e.createdAt)}</time></div><p className="mt-1 break-words text-xs text-slate-500">{e.actor}</p>{e.note&&<p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-700">{e.note}</p>}{e.kind==='UPDATED'&&changes.length>0&&<ul className="mt-3 space-y-2 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{changes.map(k=><li key={k} className="break-words"><b>{fields[k]}:</b> {display(k,before[k])} → <span className="font-medium text-slate-900">{display(k,after[k])}</span></li>)}</ul>}{e.kind==='REFERENCES'&&<dl className="mt-2 grid grid-cols-2 gap-2 text-xs text-slate-600">{Object.entries({responsible:'Responsável',supplier:'Fornecedor',requisition:'SC',purchaseOrder:'Pedido'}).map(([k,label])=><div key={k}><dt>{label}</dt><dd className="break-words font-medium">{display(k,after[k])}</dd></div>)}</dl>}{e.kind==='MAINTENANCE'&&<p className="mt-2 break-words text-xs text-slate-600">{Array.isArray(e.after)&&e.after.length?e.after.map(v=>object(v).title).join(' · '):'Nenhuma manutenção vinculada.'}</p>}{e.kind==='MAINTENANCE_SERVICE'&&typeof after.maintenanceId==='string'&&<a className="subtle-link mt-2 inline-block" href={`/manutencoes/${after.maintenanceId}`}>Abrir manutenção: {String(after.title??'')}</a>}{e.kind==='PURCHASE'&&typeof after.purchaseId==='string'&&<a className="subtle-link mt-2 inline-block" href={`/compras/${after.purchaseId}`}>Abrir compra relacionada</a>}{e.kind==='ATTACHMENT'&&typeof after.attachmentId==='string'&&<a className="subtle-link mt-2 inline-block" href={`/api/admin/incident-attachments/${after.attachmentId}`}>Baixar anexo</a>}<details className="mt-2 text-xs text-slate-400"><summary className="cursor-pointer">Dados preservados do evento</summary><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({id:e.id,before:e.before,after:e.after},null,2)}</pre></details></li>;})}</ol>}</section>;
}
