'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {z} from 'zod';
import {maintenanceSchema,maintenanceStages,maintenanceKinds,closedMaintenance} from '@/lib/maintenance';
import type {getMaintenanceOptions} from '@/lib/maintenance-options';
import {Button} from './ui/button';
type Input=z.infer<typeof maintenanceSchema>;
export type MaintenanceFormRecord=Partial<Input>&{id:string;revision:number;vehicleId:string;unavailableUntil?:string|null};
const localDate=(date?:string|null)=>date?new Date(new Date(date).getTime()-3*3600000).toISOString().slice(0,16):'';
export function MaintenanceForm({record,options,initialVehicleId='',initialIncidentId=''}:{record?:MaintenanceFormRecord;options:Awaited<ReturnType<typeof getMaintenanceOptions>>;initialVehicleId?:string;initialIncidentId?:string}){
 const router=useRouter();const key=useRef('');const [vehicle,setVehicle]=useState(record?.vehicleId??initialVehicleId),[stage,setStage]=useState(record?.stage??'REQUESTED'),[newStaff,setNewStaff]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const text=(name:string)=>String(form.get(name)??'');const ref=(name:string)=>text(name)||null;const number=(name:string)=>text(name)===''?null:Number(text(name));const date=(name:'enteredAt'|'scheduledAt'|'expectedAt'|'unavailableFrom'|'completedAt')=>text(name)===localDate(record?.[name])?record?.[name]??null:text(name)?new Date(`${text(name)}:00-03:00`).toISOString():null;
 try{key.current ||= crypto.randomUUID();const data={id:record?.id,revision:record?.revision,submissionKey:record?.submissionKey??key.current,operatorName:text('operatorName'),operatorId:text('operatorId'),vehicleId:vehicle,stage,kind:text('kind'),title:text('title'),description:text('description'),serviceOrder:ref('serviceOrder'),incidentId:ref('incidentId'),requisitionId:ref('requisitionId'),purchaseOrderId:ref('purchaseOrderId'),supplierId:ref('supplierId'),responsibleId:newStaff?null:ref('responsibleId'),...(newStaff?{newResponsible:{name:text('responsibleName'),employeeId:text('responsibleEmployeeId')}}:{}),budget:number('budget'),approvedAmount:number('approvedAmount'),cost:number('cost'),mileage:number('mileage'),enteredAt:date('enteredAt'),scheduledAt:date('scheduledAt'),expectedAt:date('expectedAt'),unavailableFrom:record?.unavailableFrom??date('unavailableFrom'),completedAt:closedMaintenance(stage)?date('completedAt'):null,solution:text('solution'),note:text('note'),alertAfterHours:Number(text('alertAfterHours')),criticalAfterHours:Number(text('criticalAfterHours'))};
 const response=await fetch('/api/admin/maintenance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw new Error(body.error??'Não foi possível salvar.');router.push(`/manutencoes/${body.id}`);router.refresh();
 }catch(e){setError(e instanceof Error?e.message:'Falha de conexão. Tente novamente.');}finally{setBusy(false);}}
 const select=(name:string,label:string,list:{id:string;label:string}[],value?:string|null)=><label className="grid min-w-0 gap-1 text-sm">{label}<select aria-label={label} className="field w-full" name={name} defaultValue={value??''}><option value="">Não definido</option>{list.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>{!list.length&&<span className="text-xs text-slate-500">Nenhum cadastro disponível.</span>}</label>;
 const dates=(name:'enteredAt'|'scheduledAt'|'expectedAt'|'unavailableFrom'|'completedAt',label:string,required=false)=><label className="grid min-w-0 gap-1 text-sm">{label}<input name={name} type="datetime-local" className="field w-full min-w-0" defaultValue={localDate(record?.[name])} required={required} readOnly={name==='unavailableFrom'&&!!record?.unavailableFrom}/></label>;
 return <form onSubmit={save} className="rounded-xl border border-slate-200 bg-white p-5"><fieldset disabled={busy} className="grid min-w-0 gap-6"><div className="grid gap-4 sm:grid-cols-2"><label className="grid min-w-0 gap-1 text-sm">Veículo<select className="field w-full" value={vehicle} disabled={!!record} onChange={e=>setVehicle(e.target.value)} required><option value="">Selecione</option>{options.vehicles.filter(v=>v.active||v.id===record?.vehicleId).map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label><label className="grid gap-1 text-sm">Tipo<select aria-label="Tipo" name="kind" className="field" defaultValue={record ? record.kind??'' : 'CORRECTIVE'} required><option value="">Selecione</option>{Object.entries(maintenanceKinds).filter(([k])=>k!=='UNSPECIFIED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="grid gap-1 text-sm">Status<select aria-label="Status" className="field" value={stage} onChange={e=>setStage(e.target.value as typeof stage)}>{Object.entries(maintenanceStages).filter(([k])=>k!=='CANCELED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="grid gap-1 text-sm">OS<input name="serviceOrder" className="field" maxLength={80} defaultValue={record?.serviceOrder??''}/></label></div>
 <label className="grid gap-1 text-sm">Problema / serviço<input name="title" className="field" required minLength={5} maxLength={200} defaultValue={record?.title??''}/></label><label className="grid gap-1 text-sm">Descrição<textarea name="description" className="field" rows={3} maxLength={5000} defaultValue={record?.description??''}/></label>
 <div key={vehicle} className="grid gap-4 sm:grid-cols-2">{select('incidentId','Ocorrência relacionada',options.incidents.filter(i=>i.vehicleId===vehicle),record?.incidentId??initialIncidentId)}{select('supplierId','Fornecedor',options.suppliers.filter(s=>s.active||s.id===record?.supplierId),record?.supplierId)}{select('requisitionId','SC',options.scs,record?.requisitionId)}{select('purchaseOrderId','Pedido',options.orders.filter(o=>!o.vehicleId||o.vehicleId===vehicle),record?.purchaseOrderId)}</div>
 <div>{!newStaff&&select('responsibleId','Responsável pelo serviço',options.staff.filter(s=>s.active||s.id===record?.responsibleId),record?.responsibleId)}<label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={newStaff} onChange={e=>setNewStaff(e.target.checked)}/>Cadastrar responsável</label>{newStaff&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Nome do responsável<input name="responsibleName" className="field" required minLength={3} maxLength={100}/></label><label className="grid gap-1 text-sm">Matrícula do responsável<input name="responsibleEmployeeId" className="field" required maxLength={60}/></label></div>}</div>
 <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-semibold">Datas e indisponibilidade</legend>{dates('scheduledAt','Programação',stage==='SCHEDULED')}{dates('enteredAt','Data de entrada',['IN_SERVICE','TESTING','DONE'].includes(stage))}{dates('expectedAt','Previsão de conclusão')}{dates('unavailableFrom','Indisponível desde (opcional)')}{closedMaintenance(stage)&&dates('completedAt','Conclusão (vazio = agora)')}<label className="grid gap-1 text-sm">Quilometragem<input name="mileage" type="number" min={0} max={9999999} step={1} className="field" defaultValue={record?.mileage??''}/></label><p className="text-xs leading-relaxed text-slate-500 sm:col-span-2">Horário de Brasília. Informe “Indisponível desde” somente quando o veículo sair de operação. A solicitação e a programação não iniciam o tempo parado. O início registrado é preservado; a conclusão encerra este período.</p></fieldset>
 <div className="grid gap-4 sm:grid-cols-3">{[['budget','Orçamento'],['approvedAmount','Valor aprovado'],['cost','Valor realizado']].map(([name,label])=><label key={name} className="grid min-w-0 gap-1 text-sm">{label} (R$)<input name={name} type="number" min={0} step="0.01" max={9999999999.99} className="field w-full" defaultValue={record?.[name as 'cost']??''}/></label>)}</div>
 <details className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">Limites dos alertas</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Atenção após (horas)<input className="field" name="alertAfterHours" type="number" min={1} max={8760} required defaultValue={record?.alertAfterHours??48}/></label><label className="grid gap-1 text-sm">Crítico após (horas)<input className="field" name="criticalAfterHours" type="number" min={1} max={17520} required defaultValue={record?.criticalAfterHours??120}/></label></div><p className="mt-3 text-xs text-slate-500">Considera tempo sem mudar de etapa e indisponibilidade. Previsão vencida gera alerta urgente. Comentários não reiniciam o relógio da etapa.</p></details>
 <label className="grid gap-1 text-sm">Solução aplicada {closedMaintenance(stage)?'(obrigatória)':'(opcional)'}<textarea name="solution" className="field" rows={3} required={closedMaintenance(stage)} minLength={5} maxLength={5000} defaultValue={record?.solution??''}/></label><label className="grid gap-1 text-sm">Observação deste atendimento<textarea name="note" className="field" rows={2} maxLength={5000}/></label>
 <div className="grid gap-3 rounded-lg bg-blue-50 p-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Seu nome<input name="operatorName" required minLength={3} maxLength={100} className="field"/></label><label className="grid gap-1 text-sm">Sua matrícula / identificação<input name="operatorId" required maxLength={60} className="field"/></label><p className="text-xs text-slate-600 sm:col-span-2">Identificação autodeclarada no ambiente local, ainda sem login. Cada alteração fica registrada no histórico.</p></div><p className="text-xs leading-relaxed text-amber-900">Concluir o serviço não libera restrições operacionais. Após a última manutenção com indisponibilidade, a disponibilidade fica não informada até a conferência da Frota.</p><Button type="submit">{busy?'Salvando…':record?'Salvar atendimento':'Solicitar manutenção'}</Button></fieldset>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}</form>;
}
