'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button} from './ui/button';
import {safetyNotice} from '@/lib/restrictions';
export function RestrictionPolicyForm({policy,updatedAt}:{policy:{initialState:string;releaseEvidenceRequired:boolean};updatedAt:string}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget);try{
  const response=await fetch('/api/admin/restriction-policy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({updatedAt,operatorName:form.get('operatorName'),operatorId:form.get('operatorId'),policy:{initialState:form.get('initialState'),releaseEvidenceRequired:form.has('releaseEvidenceRequired')}})});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage('Configuração salva.');router.refresh();
 }catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <form onSubmit={save} className="mt-5 max-w-2xl rounded-xl border border-slate-200 bg-white p-5"><fieldset disabled={busy} className="grid gap-5"><label className="grid gap-2 text-sm">Estado inicial ao acionar uma regra de bloqueio<select name="initialState" className="field" defaultValue={policy.initialState}><option value="AWAITING_ASSESSMENT">Aguardando avaliação</option><option value="BLOCKED">Bloqueado</option></select></label><p className="text-sm text-slate-500">Ambos os estados deixam o veículo indisponível. A criticidade e o acionamento de bloqueio continuam definidos por item do checklist.</p><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" name="releaseEvidenceRequired" defaultChecked={policy.releaseEvidenceRequired}/>Exigir foto ou documento para registrar uma liberação</label><p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">A configuração vale para novas restrições. As restrições existentes preservam a exigência definida na abertura.</p><label className="grid gap-1 text-sm">Seu nome<input required minLength={3} maxLength={100} name="operatorName" className="field"/></label><label className="grid gap-1 text-sm">Sua matrícula / identificação<input required maxLength={60} name="operatorId" className="field"/></label><p className="text-xs text-slate-500">Identificação autodeclarada no ambiente local. Alterações de configuração são auditadas.</p><p className="text-xs leading-relaxed text-slate-600">{safetyNotice}</p><Button type="submit">{busy?'Salvando…':'Salvar configuração'}</Button></fieldset>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}</form>;
}
