import Link from 'next/link';


import {notFound} from 'next/navigation';
import {prisma} from '@/lib/prisma';
import {vehicleTabs,vehicleRecordWhere,displayPlate,type VehicleTab} from '@/lib/vehicle-record';
import {getVehicleTimeline} from '@/lib/vehicle-timeline';
import {preventiveState} from '@/lib/preventive';
import {date,integer} from '@/lib/utils';
import {incidentDate} from '@/lib/incidents';
import {StatusBadge} from './status-badge';
import {PreventiveBadge} from './preventive-badge';
import {RestrictionBanner} from './restriction-banner';
import {VehicleRestrictions} from './vehicle-restrictions';
import {VehicleHistory} from './vehicle-history';
import {VehicleRecordTab} from './vehicle-record-tabs';
import {ModuleRefresh} from './module-refresh';
import {VehicleQrPanel} from './vehicle-qr-panel';
export default async function VehicleRecordPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {id:identifier}=await params;if(identifier.length>100)notFound();const paramsSearch=await searchParams;
 const tab:VehicleTab=typeof paramsSearch.tab==='string'&&Object.hasOwn(vehicleTabs,paramsSearch.tab)?paramsSearch.tab as VehicleTab:'resumo';
 const page=Math.max(1,Math.min(100000,Math.floor(Number(paramsSearch.page)||1)));
 const v=await prisma.vehicle.findUnique({where:vehicleRecordWhere(identifier),include:{costCenter:true,preventivePlan:true,preventives:{where:{completedAt:null},orderBy:{dueAt:'asc'},take:1},checklists:{where:{status:{in:['SUBMITTED','REVIEWED']}},orderBy:{submittedAt:'desc'},take:1,select:{driverName:true,driverIdentification:true,submittedAt:true,id:true}},_count:{select:{checklists:true,incidents:true,maintenance:true,preventives:true,tires:true,documents:true,fuelRecords:true}}}});if(!v)notFound();
 const open=await prisma.incident.count({where:{vehicleId:v.id,status:{in:['OPEN','IN_PROGRESS']}}});const lastDriver=v.checklists[0],legacy=v.preventives[0];
 const nextMileage=v.preventivePlan?v.preventivePlan.nextMileage:legacy?.dueMileage??null,nextDate=v.preventivePlan?v.preventivePlan.dueAt:legacy?.dueAt??null;
 const planState=v.preventivePlan?preventiveState(v.preventivePlan,v.mileage):legacy?preventiveState({nextMileage:legacy.dueMileage,dueAt:legacy.dueAt,toleranceKm:0,toleranceDays:0,upcomingKm:1000,upcomingDays:7},v.mileage):null;
 const status=v.operationalStatus!=='CLEAR'?v.operationalStatus:!v.active?'INACTIVE':v.status;
 const availability=!v.active?'Inativo':v.operationalStatus!=='CLEAR'?'Indisponível':({AVAILABLE:'Disponível',UNAVAILABLE:'Indisponível',UNKNOWN:'Não informada'} as Record<string,string>)[v.availability]??'Não informada';
 const href=(t:VehicleTab)=>`/frota/${v.plate}?tab=${t}`;
 const counts:Partial<Record<VehicleTab,number>>={checklists:v._count.checklists,ocorrencias:v._count.incidents,manutencoes:v._count.maintenance,preventivas:v._count.preventives+(v.preventivePlan?1:0),pneus:v._count.tires,abastecimentos:v._count.fuelRecords,documentos:v._count.documents};
 const history=tab==='resumo'?await getVehicleTimeline(v.id,1,8):null;
 const qrEvents=tab==='resumo'?await prisma.vehicleQrEvent.findMany({where:{vehicleId:v.id},orderBy:[{createdAt:'desc'},{id:'desc'}]}):[];
 return <div className="page operational-page incident-page"><Link href="/frota" className="subtle-link mb-5">← Voltar à frota</Link><header className="page-heading"><div className="min-w-0"><div className="eyebrow">FICHA DO VEÍCULO{v.code?` · ${v.code}`:''}</div><h1>{displayPlate(v.plate)}</h1><p className="break-words">{v.model} · {v.year}</p></div><div className="flex flex-wrap items-center gap-3"><span className="text-sm">Status:</span><StatusBadge status={status}/><ModuleRefresh interval={false}/></div></header><RestrictionBanner status={v.operationalStatus}/><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Summary label="KM atual" value={v.mileage===null?'Não informado':`${integer(v.mileage)} km`} href={`/preventivas/${v.id}`} note="Leituras e histórico do hodômetro"/><Summary label="Centro de custo" value={v.costCenter?`${v.costCenter.code} · ${v.costCenter.name}`:'Não informado'} note={v.unit?`Unidade: ${v.unit}`:'Unidade não informada'}/><Summary label="Motorista · último checklist" value={lastDriver?.driverName??'Não informado'} href={lastDriver?`/checklists/${lastDriver.id}`:undefined} note={lastDriver?`${incidentDate(lastDriver.submittedAt)} · não indica vínculo fixo`:'Sem checklist válido registrado'}/><Summary label="Próxima preventiva" value={nextMileage===null?'KM não definido':`${integer(nextMileage)} km`} href={href('preventivas')} note={nextDate?`Data prevista: ${date(nextDate)}`:'Data prevista não definida'}><PreventiveBadge status={planState?.status??'UNKNOWN'}/>{planState?.remainingKm!==null&&planState?.remainingKm!==undefined&&<small className="mt-2 block text-xs text-slate-600">{planState.remainingKm>=0?`Faltam ${integer(planState.remainingKm)} km`:`${integer(Math.abs(planState.remainingKm))} km acima do limite`}</small>}</Summary><Summary label="Disponibilidade" value={availability} note="Situação operacional registrada"/><Summary label="Ocorrências abertas" value={String(open)} href={href('ocorrencias')} note={`${v._count.incidents} ocorrências no histórico`}/></div><nav aria-label="Abas da ficha do veículo" className="mb-6 flex max-w-full flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-3">{Object.entries(vehicleTabs).map(([key,label])=><Link key={key} href={href(key as VehicleTab)} aria-current={key===tab?'page':undefined} className={`rounded-lg px-3 py-2 text-xs font-semibold ${key===tab?'bg-emerald-700 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label.toUpperCase()}{counts[key as VehicleTab]!==undefined&&<span className="ml-2 opacity-70">{counts[key as VehicleTab]}</span>}</Link>)}</nav><section aria-label={vehicleTabs[tab]}>
 {tab==='resumo'?<><div className="grid min-w-0 items-start gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]"><div className="min-w-0"><section className="mb-5 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Dados do veículo</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2">{[['Placa',v.plate],['Prefixo',v.code??'Não informado'],['Marca',v.brand??'Não informada'],['Modelo',v.model],['Ano',String(v.year)],['Tipo',v.category],['Perfil',v.profile??'Não informado'],['Cubagem',v.cargoVolumeM3===null?'Não informada':`${Number(v.cargoVolumeM3).toLocaleString('pt-BR')} m³`]].map(([label,value])=><div key={label} className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl>{v.notes&&<p className="mt-5 whitespace-pre-wrap break-words text-sm"><strong>Observações:</strong> {v.notes}</p>}<div className="mt-5 flex flex-wrap gap-4"><Link href={`/manutencoes/nova?vehicle=${v.id}`} className="subtle-link">Solicitar manutenção →</Link><Link href={`/compras/nova?vehicle=${v.id}`} className="subtle-link">Solicitar compra →</Link><Link href={`/preventivas/${v.id}`} className="subtle-link">Configurar preventiva →</Link></div></section><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Timeline geral do veículo</h2><Link href={href('historico')} className="subtle-link">Ver histórico completo →</Link></div><VehicleHistory rows={history?.rows??[]}/></section></div><VehicleQrPanel key={`${v.id}:${v.qrRevision}`} vehicleId={v.id} revision={v.qrRevision} rotatedAt={v.qrRotatedAt?.toISOString()??null} events={qrEvents.map(e=>({id:e.id,actor:e.actor,reason:e.reason,createdAt:e.createdAt.toISOString()}))}/></div><VehicleRestrictions vehicleId={v.id} showBanner={false}/></>:<VehicleRecordTab id={v.id} plate={v.plate} tab={tab} page={page} mileage={v.mileage}/>}
 </section></div>;
}
function Summary({label,value,note,href,children}:{label:string;value:string;note:string;href?:string;children?:React.ReactNode}){const content=<><p className="text-xs text-slate-500">{label}</p><strong className="mt-2 block break-words text-lg">{value}</strong><p className="mt-1 text-xs text-slate-500">{note}</p>{children&&<div className="mt-2">{children}</div>}</>;return href?<Link href={href} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 hover:border-emerald-500">{content}</Link>:<div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4">{content}</div>;}
