'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {fuelTypes} from '@/lib/vehicle-record';
import {Button} from './ui/button';
export function VehicleFuelForm({vehicleId,now}:{vehicleId:string;now:string}){
 const router=useRouter(),key=useRef('');const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),text=(k:string)=>String(f.get(k)??'');setBusy(true);setMessage('');
 try{key.current ||= crypto.randomUUID();const r=await fetch('/api/admin/fuel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId,submissionKey:key.current,fueledAt:new Date(`${text('fueledAt')}:00-03:00`).toISOString(),mileage:Number(text('mileage')),fuelType:text('fuelType'),liters:Number(text('liters')),amount:Number(text('amount')),station:text('station'),notes:text('notes'),operatorName:text('operatorName'),operatorId:text('operatorId')})});const data=await r.json();if(!r.ok)throw new Error(data.error);key.current='';form.reset();setMessage('Abastecimento registrado.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Falha de conexão.');}finally{setBusy(false);}}
 return <details className="mb-5 rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-semibold">Registrar abastecimento</summary><form onSubmit={submit} className="mt-5"><fieldset disabled={busy} className="grid min-w-0 gap-4 sm:grid-cols-2"><label className="grid min-w-0 gap-1 text-sm">Data/hora do abastecimento<input name="fueledAt" type="datetime-local" className="field min-w-0 w-full" required defaultValue={new Date(new Date(now).getTime()-3*3600000).toISOString().slice(0,16)}/></label><label className="grid min-w-0 gap-1 text-sm">Combustível / insumo<select name="fuelType" aria-label="Combustível / insumo" className="field min-w-0" required defaultValue=""><option value="">Selecione</option>{Object.entries(fuelTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{[['mileage','KM no abastecimento','1','0','9999999'],['liters','Litros','0.001','0.001','9999999.999'],['amount','Valor total (R$)','0.01','0','9999999999.99']].map(([k,label,step,min,max])=><label key={k} className="grid min-w-0 gap-1 text-sm">{label}<input name={k} className="field min-w-0 w-full" type="number" step={step} min={min} max={max} required/></label>)}<label className="grid min-w-0 gap-1 text-sm">Posto / fornecedor<input name="station" className="field min-w-0" maxLength={150}/></label><label className="grid gap-1 text-sm sm:col-span-2">Observação<textarea name="notes" className="field" rows={2} maxLength={2000}/></label><label className="grid min-w-0 gap-1 text-sm">Seu nome<input name="operatorName" className="field min-w-0" required minLength={3} maxLength={100}/></label><label className="grid min-w-0 gap-1 text-sm">Sua matrícula / identificação<input name="operatorId" className="field min-w-0" required maxLength={60}/></label><p className="text-xs leading-relaxed text-slate-500 sm:col-span-2">Horário de Brasília. Este registro preserva os dados informados e não altera o KM atual do veículo. Confira os valores antes de salvar: o registro permanece no histórico. Identificação autodeclarada no ambiente local.</p><Button type="submit">{busy?'Salvando…':'Salvar abastecimento'}</Button></fieldset>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}</form></details>;
}
