import Link from 'next/link';
import type {ReactNode} from 'react';
import {prisma} from '@/lib/prisma';
import {incidentDate} from '@/lib/incidents';
import {currency,date,integer} from '@/lib/utils';
import {StatusBadge} from './status-badge';
import {IncidentStageBadge} from './incident-stage';
import {MaintenanceStageBadge} from './maintenance-stage';
import {PurchaseStageBadge} from './purchase-stage';
import {PreventiveBadge} from './preventive-badge';
import {VehicleFuelForm} from './vehicle-fuel-form';
import {VehicleHistory} from './vehicle-history';
import {getVehicleTimeline} from '@/lib/vehicle-timeline';
import {preventiveState} from '@/lib/preventive';
import {maintenanceKinds,elapsedLabel} from '@/lib/maintenance';
import {fuelTypes,safeDocumentUrl,type VehicleTab} from '@/lib/vehicle-record';
function Table({columns,children,empty}:{columns:string[];children:ReactNode;empty:boolean}){return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="op-table-scroll" role="region" aria-label="Registros do veículo" tabIndex={0}><table className="op-table" style={{minWidth:900}}><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{children}</tbody></table></div>{empty&&<p className="p-6 text-sm text-slate-500">Nenhum registro encontrado para este veículo.</p>}</div>;}
function Pager({plate,tab,page,total}:{plate:string;tab:string;page:number;total:number}){return <div className="mt-4 flex flex-wrap justify-between gap-3 text-xs text-slate-500"><span>{total} registros · página {page}</span><div className="flex gap-4">{page>1&&<Link href={`/frota/${plate}?tab=${tab}&page=${page-1}`}>← Anterior</Link>}{page*20<total&&<Link href={`/frota/${plate}?tab=${tab}&page=${page+1}`}>Próxima →</Link>}</div></div>;}
export async function VehicleRecordTab({id,plate,tab,page,mileage}:{id:string;plate:string;tab:VehicleTab;page:number;mileage:number|null}){
 const where={vehicleId:id},pagination={take:20,skip:(page-1)*20};
 if(tab==='checklists'){
  const [rows,total]=await prisma.$transaction([prisma.checklist.findMany({where,orderBy:[{submittedAt:'desc'},{id:'desc'}],...pagination}),prisma.checklist.count({where})]);
  return <><Table columns={['Data/hora','Motorista / identificação','KM','Conformidade','Resultado','Ação']} empty={!rows.length}>{rows.map(c=><tr key={c.id}><td>{incidentDate(c.submittedAt)}</td><td>{c.driverName}<small className="block text-slate-500">{c.driverIdentification??'Identificação não informada'}</small></td><td>{integer(c.mileage)} km</td><td>{c.conformityPercentage===null?'Não avaliada':`${Number(c.conformityPercentage).toLocaleString('pt-BR')}%`}</td><td><StatusBadge status={c.result}/></td><td><Link className="subtle-link" href={`/checklists/${c.id}`}>Checklist e fotos →</Link></td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='ocorrencias'){
  const [rows,total]=await prisma.$transaction([prisma.incident.findMany({where,include:{responsible:true},orderBy:[{openedAt:'desc'},{id:'desc'}],...pagination}),prisma.incident.count({where})]);
  return <><Table columns={['Número','Problema','Criticidade','Abertura','Responsável','Status','Prazo','Ação']} empty={!rows.length}>{rows.map(i=><tr key={i.id}><td>{i.publicNumber}</td><td className="op-problem">{i.title}</td><td><StatusBadge status={i.priority}/></td><td>{incidentDate(i.openedAt)}</td><td>{i.responsible?.name??'Não atribuído'}</td><td><IncidentStageBadge stage={i.stage}/></td><td>{i.dueAt?incidentDate(i.dueAt):'Não definido'}</td><td><Link className="subtle-link" href={`/ocorrencias/${i.id}`}>Atendimento →</Link></td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='manutencoes'){
  const [rows,total]=await prisma.$transaction([prisma.maintenance.findMany({where,include:{supplier:true,responsible:true},orderBy:[{createdAt:'desc'},{id:'desc'}],...pagination}),prisma.maintenance.count({where})]);
  return <><Link href={`/manutencoes/nova?vehicle=${id}`} className="subtle-link mb-4">Solicitar manutenção →</Link><Table columns={['OS / serviço','Tipo','Fornecedor','Entrada / previsão','Indisponibilidade','Valor realizado','Responsável','Status','Ação']} empty={!rows.length}>{rows.map(m=><tr key={m.id}><td className="op-problem"><strong>{m.serviceOrder??'Sem OS'}</strong><p>{m.title}</p></td><td>{maintenanceKinds[m.kind]}</td><td>{m.supplier?.name??'Não definido'}</td><td>{m.enteredAt?incidentDate(m.enteredAt):'Sem entrada'}<small className="block">{m.expectedAt?incidentDate(m.expectedAt):'Sem previsão'}</small></td><td>{elapsedLabel(m.unavailableFrom,m.unavailableUntil)}</td><td>{m.costKnown?currency(Number(m.cost)):'Não informado'}</td><td>{m.responsible?.name??'Não definido'}</td><td><MaintenanceStageBadge stage={m.stage}/></td><td><Link href={`/manutencoes/${m.id}`} className="subtle-link">Abrir →</Link></td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='preventivas'){
  const [plan,rows,total]=await prisma.$transaction([prisma.preventivePlan.findUnique({where:{vehicleId:id}}),prisma.preventive.findMany({where,orderBy:[{dueAt:'desc'},{id:'desc'}],...pagination}),prisma.preventive.count({where})]);const state=plan?preventiveState(plan,mileage):null;
  return <><section className="mb-5 rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">Plano preventivo atual</h2><PreventiveBadge status={state?.status??'UNKNOWN'}/></div>{plan?<dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3">{[['Intervalo',plan.intervalKm===null?'Não informado':`${integer(plan.intervalKm)} km`],['Último KM',plan.lastMileage===null?'Não informado':`${integer(plan.lastMileage)} km`],['Próximo KM',plan.nextMileage===null?'Não informado':`${integer(plan.nextMileage)} km`],['Última data',plan.lastAt?date(plan.lastAt):'Não informada'],['Data prevista',plan.dueAt?date(plan.dueAt):'Não definida'],['Tolerância',`${integer(plan.toleranceKm)} km · ${plan.toleranceDays} dias`]].map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-1">{v}</dd></div>)}</dl>:<p className="mt-3 text-sm text-slate-500">Nenhum plano configurado.</p>}<Link href={`/preventivas/${id}`} className="subtle-link mt-5">Configurar plano e consultar leituras de KM →</Link></section><h2 className="mb-3 font-semibold">Programações anteriores</h2><Table columns={['Serviço','Limite por KM','Data prevista','Conclusão']} empty={!rows.length}>{rows.map(p=><tr key={p.id}><td>{p.title}</td><td>{integer(p.dueMileage)} km</td><td>{date(p.dueAt)}</td><td>{p.completedAt?date(p.completedAt):'Pendente'}</td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='pneus'){
  const [rows,total]=await prisma.$transaction([prisma.tire.findMany({where,orderBy:[{position:'asc'},{id:'asc'}],...pagination}),prisma.tire.count({where})]);
  return <><p className="mb-4 text-xs text-slate-500">Pneus atualmente vinculados. Movimentações anteriores de pneus ainda não possuem histórico específico no cadastro.</p><Table columns={['Identificação','Marca','Posição','Sulco','Status','Cadastro']} empty={!rows.length}>{rows.map(t=><tr key={t.id}><td>{t.serial}</td><td>{t.brand}</td><td>{t.position}</td><td>{Number(t.treadMm).toLocaleString('pt-BR')} mm</td><td>{t.status}</td><td>{date(t.createdAt)}</td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='abastecimentos'){
  const [rows,total]=await prisma.$transaction([prisma.fuelRecord.findMany({where,orderBy:[{fueledAt:'desc'},{id:'desc'}],...pagination}),prisma.fuelRecord.count({where})]);
  return <><VehicleFuelForm vehicleId={id} now={new Date().toISOString()}/><Table columns={['Data/hora','KM','Combustível / insumo','Litros','Valor total','Posto','Observação','Registrado por']} empty={!rows.length}>{rows.map(f=><tr key={f.id}><td>{incidentDate(f.fueledAt)}</td><td>{integer(f.mileage)} km</td><td>{fuelTypes[f.fuelType as keyof typeof fuelTypes]??f.fuelType}</td><td>{Number(f.liters).toLocaleString('pt-BR')}</td><td>{currency(Number(f.amount))}</td><td>{f.station||'Não informado'}</td><td className="max-w-64 break-words">{f.notes||'—'}</td><td>{f.actor}</td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='custos'){
  const purchaseWhere={OR:[{vehicleId:id},{incidents:{some:{vehicleId:id}}},{maintenance:{some:{vehicleId:id}}}]};
  const [maintenance,fuel,purchases,missing,orders,total]=await prisma.$transaction([prisma.maintenance.aggregate({where:{...where,costKnown:true},_sum:{cost:true},_count:true}),prisma.fuelRecord.aggregate({where,_sum:{amount:true},_count:true}),prisma.purchaseOrder.aggregate({where:{...purchaseWhere,amountKnown:true,stage:{notIn:['REJECTED','CANCELED']}},_sum:{amount:true},_count:true}),prisma.maintenance.count({where:{...where,costKnown:false}}),prisma.purchaseOrder.findMany({where:purchaseWhere,include:{requisition:true,supplier:true},orderBy:[{requestedAt:'desc'},{id:'desc'}],...pagination}),prisma.purchaseOrder.count({where:purchaseWhere})]);
  return <><p className="mb-4 rounded-lg bg-blue-50 p-4 text-sm text-blue-900">Valores de todo o período registrado. Pedidos de compra são compromissos e podem compor o valor de uma manutenção; não são somados aos realizados. Estes registros não representam um fechamento contábil.</p><div className="mb-5 grid gap-3 sm:grid-cols-3">{[['Manutenções · realizado informado',maintenance._count?currency(Number(maintenance._sum.cost)):'Não informado',`${maintenance._count} registros com valor · ${missing} sem valor realizado`],['Abastecimentos · total registrado',fuel._count?currency(Number(fuel._sum.amount)):'Não informado',`${fuel._count} registros`],['Compras · valores não recusados/cancelados',purchases._count?currency(Number(purchases._sum.amount)):'Não informado',`${purchases._count} pedidos/solicitações com valor`]].map(([label,value,note])=><div className="min-w-0 rounded-xl border border-slate-200 bg-white p-5" key={label}><p className="text-xs text-slate-500">{label}</p><strong className="mt-3 block break-words text-xl">{value}</strong><p className="mt-2 text-xs text-slate-500">{note}</p></div>)}</div><div className="mb-4 flex flex-wrap gap-4"><Link href={`/frota/${plate}?tab=manutencoes`} className="subtle-link">Detalhar manutenção →</Link><Link href={`/frota/${plate}?tab=abastecimentos`} className="subtle-link">Detalhar abastecimentos →</Link><Link href={`/compras/nova?vehicle=${id}`} className="subtle-link">Solicitar compra →</Link></div><Table columns={['SC','Pedido','Descrição','Fornecedor','Valor','Status','Ação']} empty={!orders.length}>{orders.map(p=><tr key={p.id}><td>{p.requisition?.number??'Não informada'}</td><td>{p.orderNumber??'Ainda não gerado'}</td><td className="op-problem">{p.description}</td><td>{p.supplier?.name??'Não definido'}</td><td>{p.amountKnown?currency(Number(p.amount)):'Não informado'}</td><td><PurchaseStageBadge stage={p.stage}/></td><td><Link href={`/compras/${p.id}`} className="subtle-link">Abrir →</Link></td></tr>)}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='documentos'){
  const [rows,total]=await prisma.$transaction([prisma.document.findMany({where,orderBy:[{expiresAt:'asc'},{id:'asc'}],...pagination}),prisma.document.count({where})]);
  return <><Table columns={['Documento','Validade','Situação','Arquivo']} empty={!rows.length}>{rows.map(d=>{const href=safeDocumentUrl(d.fileUrl),today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia'}).format(new Date()),expiry=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia'}).format(d.expiresAt);return <tr key={d.id}><td>{d.title}</td><td>{date(d.expiresAt)}</td><td><StatusBadge status={expiry<today?'OVERDUE':'OK'}/></td><td>{href?<a href={href} target="_blank" rel="noopener noreferrer" className="subtle-link">Abrir documento →</a>:<span className="text-slate-500">Arquivo não disponível</span>}</td></tr>;})}</Table><Pager {...{plate,tab,page,total}}/></>;
 }
 if(tab==='historico'){
  const history=await getVehicleTimeline(id,page,20);
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-2 font-semibold">Timeline geral do veículo</h2><p className="mb-6 text-xs leading-relaxed text-slate-500">Eventos mais recentes primeiro, com acesso ao registro de origem. Datas de serviço informadas podem anteceder o cadastro. SCs e compras consideram vínculos atuais; alterações de veículo em compras também preservam seus snapshots históricos. Ausência de evento não comprova ausência de serviço.</p><VehicleHistory rows={history.rows}/><Pager {...{plate,tab,page,total:history.total}}/></section>;
 }
 return null;
}
