import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import {prisma as db} from '../src/lib/prisma';
import {syncAlertSources} from '../src/lib/alert-sources';
import {syncMaintenanceAlerts} from '../src/lib/maintenance-alerts';
import {syncPreventiveAlerts} from '../src/lib/preventive-alerts';
async function main(){
 const before=JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}})),base='http://127.0.0.1:3000',tag=`QA-${crypto.randomUUID()}`;
 const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(60000);await page.emulateMedia({reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let vehicleId:string|undefined;
 try{
  const v=await db.vehicle.create({data:{plate:'ZZZ2Z22',model:'Validação de alertas',category:'Caminhão',year:2020,mileage:50000}});vehicleId=v.id;
  const manual=await db.alert.create({data:{vehicleId,module:'checklists',title:'Resposta negativa QA',description:'Conferir checklist',priority:'CRITICAL'}});
  const m=await db.maintenance.create({data:{vehicleId,title:'Manutenção QA',type:'Corretiva',stageChangedAt:new Date(Date.now()-72*3600000)}});
  const plan=await db.preventivePlan.create({data:{vehicleId,nextMileage:49000}});
  const doc=await db.document.create({data:{vehicleId,title:'Documento QA',expiresAt:new Date('2020-01-01')}});
  const order=await db.purchaseOrder.create({data:{vehicleId,number:`SOL-${tag}`,description:'Compra QA',amount:100,stageChangedAt:new Date(Date.now()-7*86400000)}});
  const tire=await db.tire.create({data:{vehicleId,serial:tag,brand:'Marca QA',position:'Dianteiro',treadMm:5,status:'Atenção'}});
  await db.incident.create({data:{vehicleId,title:'Ocorrência QA',description:'Pendência registrada',priority:'HIGH'}});
  await syncAlertSources();const alerts=await db.alert.findMany({where:{vehicleId}});assert.equal(alerts.length,7);assert.equal(new Set(alerts.map(a=>a.category)).size,7);
  const count=await db.alertEvent.count({where:{alert:{vehicleId}}});await syncAlertSources();assert.equal(await db.alertEvent.count({where:{alert:{vehicleId}}}),count,'Atualizar sem mudança não gera eventos nem duplica alertas');
  const send=(id:string,data:object,origin=base)=>page.request.patch(`${base}/api/admin/alerts/${id}`,{headers:{origin},data});
  let data={revision:0,stage:'IN_PROGRESS',responsibleId:null as string|null,actionRequired:'Conferir o checklist com o motorista',note:'Avaliação iniciada pelo analista',operatorName:'Analista QA',operatorId:tag};
  assert.equal((await send(manual.id,data)).status(),400);assert.equal((await send(manual.id,data,'https://invalid.example')).status(),403);assert.equal((await send(manual.id,{...data,stage:'RULE_CLOSED'})).status(),400);
  await page.goto(`${base}/alertas/${manual.id}`);await page.getByLabel('Status do alerta',{exact:true}).selectOption('IN_PROGRESS');await page.getByLabel('Cadastrar responsável',{exact:true}).check();await page.getByLabel('Nome do responsável',{exact:true}).fill('Analista QA');await page.getByLabel('Matrícula do responsável',{exact:true}).fill(tag);await page.getByLabel('Atendimento / motivo',{exact:true}).fill(data.note);await page.getByLabel('Seu nome',{exact:true}).fill(data.operatorName);await page.getByLabel('Sua matrícula / identificação',{exact:true}).fill(tag);await page.getByRole('button',{name:'Salvar atendimento'}).click();await expect.poll(async()=>(await db.alert.findUniqueOrThrow({where:{id:manual.id}})).stage,{timeout:60000}).toBe('IN_PROGRESS');
  let current=await db.alert.findUniqueOrThrow({where:{id:manual.id}});data={...data,revision:current.revision,responsibleId:current.responsibleId};assert.ok(current.responsibleId);
  const originalEvents=await db.alertEvent.findMany({where:{alertId:manual.id},orderBy:{id:'asc'}});await assert.rejects(db.alertEvent.update({where:{id:originalEvents[0].id},data:{note:'Alteração proibida'}}));await assert.rejects(db.alert.delete({where:{id:manual.id}}));
  const race=await Promise.all([send(manual.id,{...data,note:'Primeiro atendimento simultâneo'}),send(manual.id,{...data,note:'Segundo atendimento simultâneo'})]);assert.deepEqual(race.map(r=>r.status()).sort(),[200,409]);
  for(const stage of ['RESOLVED','NEW','HANDLED','NEW','NOT_APPLICABLE']){current=await db.alert.findUniqueOrThrow({where:{id:manual.id}});const response=await send(manual.id,{...data,revision:current.revision,stage,note:`Decisão de teste: ${stage}`});assert.equal(response.status(),200,await response.text());current=await db.alert.findUniqueOrThrow({where:{id:manual.id}});assert.equal(current.closedAt!==null,stage!=='NEW');}
  assert.deepEqual(await db.alertEvent.findMany({where:{id:{in:originalEvents.map(e=>e.id)}},orderBy:{id:'asc'}}),originalEvents);
  // Reading, same source sync and user comments must not reopen an acknowledged condition.
  const ma=alerts.find(a=>a.maintenanceId===m.id)!;assert.equal((await send(ma.id,{...data,revision:ma.revision,stage:'HANDLED',note:'Oficina contatada e serviço acompanhado'})).status(),200);await syncMaintenanceAlerts();assert.equal((await db.alert.findUniqueOrThrow({where:{id:ma.id}})).stage,'HANDLED');
  await db.maintenance.update({where:{id:m.id},data:{criticalAfterHours:60}});await syncMaintenanceAlerts();assert.equal((await db.alert.findUniqueOrThrow({where:{id:ma.id}})).stage,'NEW');
  await db.maintenance.update({where:{id:m.id},data:{stage:'DONE',completedAt:new Date()}});await syncMaintenanceAlerts();assert.equal((await db.alert.findUniqueOrThrow({where:{id:ma.id}})).stage,'RULE_CLOSED');
  const pa=alerts.find(a=>a.preventivePlanId===plan.id)!;assert.equal((await send(pa.id,{...data,revision:pa.revision,stage:'HANDLED',note:'Preventiva encaminhada para agendamento'})).status(),200);await syncPreventiveAlerts();assert.equal((await db.alert.findUniqueOrThrow({where:{id:pa.id}})).stage,'HANDLED');await db.preventivePlan.update({where:{id:plan.id},data:{nextMileage:60000}});await syncPreventiveAlerts();await db.preventivePlan.update({where:{id:plan.id},data:{nextMileage:49000}});await syncPreventiveAlerts();assert.equal((await db.alert.findUniqueOrThrow({where:{id:pa.id}})).stage,'NEW');
  await db.document.update({where:{id:doc.id},data:{expiresAt:new Date('2035-01-01')}});await db.purchaseOrder.update({where:{id:order.id},data:{stage:'FINISHED'}});await db.tire.update({where:{id:tire.id},data:{status:'Em uso'}});await syncAlertSources();for(const key of [`DOCUMENT:${doc.id}`,`PURCHASE:${order.id}`,`TIRE:${tire.id}`])assert.equal((await db.alert.findUniqueOrThrow({where:{sourceKey:key}})).stage,'RULE_CLOSED');
  await page.goto(`${base}/alertas?vehicle=${vehicleId}`);await expect(page.getByRole('region',{name:'Tabela de alertas'}).getByText(manual.title,{exact:true})).toHaveCount(0);await page.getByRole('link',{name:'Histórico de encerrados',exact:true}).click();await expect(page.getByRole('region',{name:'Tabela de alertas'}).getByText(manual.title,{exact:true})).toBeVisible();
  await page.goto(`${base}/alertas?view=all&vehicle=${vehicleId}&category=CHECKLIST&priority=CRITICAL`);await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByLabel('Responsável',{exact:true}).selectOption(current.responsibleId!);await page.getByRole('button',{name:'Filtrar'}).click();await expect(page.locator('tbody tr')).toHaveCount(1);
  await mkdir('test-results',{recursive:true});for(const [name,route] of [['list',`/alertas?view=all&vehicle=${vehicleId}`],['detail',`/alertas/${manual.id}`]]){await page.goto(base+route);for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/alerts-${name}-${width}.png`,fullPage:true,caret:'initial'});}}
  assert.deepEqual(errors,[]);console.log('PASS: sete categorias, fila persistente, quatro encerramentos, UI, filtros, responsável, motivos, imutabilidade, concorrência, recorrência/agravamento, regras e 1440/768/390.');
 }catch(e){console.error(errors);console.error((await page.locator('body').innerText()).slice(0,12000));throw e;}finally{await browser.close();if(vehicleId)await db.$transaction(async tx=>{await tx.alertEvent.deleteMany({where:{alert:{vehicleId}}});await tx.alert.deleteMany({where:{vehicleId}});await tx.maintenanceEvent.deleteMany({where:{maintenance:{vehicleId}}});await tx.maintenance.deleteMany({where:{vehicleId}});await tx.preventivePlan.deleteMany({where:{vehicleId}});await tx.document.deleteMany({where:{vehicleId}});await tx.purchaseEvent.deleteMany({where:{purchase:{vehicleId}}});await tx.purchaseOrder.deleteMany({where:{vehicleId}});await tx.tire.deleteMany({where:{vehicleId}});await tx.incidentEvent.deleteMany({where:{incident:{vehicleId}}});await tx.incident.deleteMany({where:{vehicleId}});await tx.vehicle.delete({where:{id:vehicleId}});await tx.staffMember.deleteMany({where:{employeeId:tag}});});assert.equal(JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}})),before,'Frota existente preservada');await db.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
