import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {PrismaClient} from '@prisma/client';
import {chromium,expect} from '@playwright/test';
import {getVehicleInspection} from '../src/lib/checklist-config';
import {preventiveState} from '../src/lib/preventive';
async function main(){
 const db=new PrismaClient(),base='http://127.0.0.1:3000',tag=`QA-${crypto.randomUUID()}`;const before=JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}}));
 const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(45000);await page.emulateMedia({reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let vehicleId:string|undefined;
 try{
  const v=await db.vehicle.create({data:{plate:'ZZZ5Z55',model:'Validação temporária preventiva',category:'Caminhão',year:2020}});vehicleId=v.id;
  await page.goto(`${base}/preventivas/${vehicleId}`);await page.getByLabel('KM atual',{exact:true}).fill('48750');await page.getByLabel('Intervalo da preventiva (km)',{exact:true}).fill('10000');await page.getByLabel('KM da última preventiva',{exact:true}).fill('40000');await expect(page.getByLabel('KM da próxima preventiva',{exact:true})).toHaveValue('50000');await page.getByLabel('Avisar quando faltarem (km)',{exact:true}).fill('1500');await page.getByLabel('Tolerância após limite (km)',{exact:true}).fill('500');await page.getByLabel('Motivo / serviço realizado',{exact:true}).fill(tag);await page.getByLabel('Seu nome',{exact:true}).fill('Analista QA');await page.getByLabel('Sua matrícula / identificação',{exact:true}).fill(tag);await page.getByRole('button',{name:'Salvar configuração',exact:true}).click();
  await expect(page.getByText('Faltam 1.250 km',{exact:true})).toBeVisible({timeout:45000});let p=await db.preventivePlan.findUniqueOrThrow({where:{vehicleId}});assert.equal(p.nextMileage,50000);assert.equal(preventiveState(p,48750).status,'UPCOMING');assert.equal(await db.mileageReading.count({where:{vehicleId,source:'ADMIN'}}),1);
  await mkdir('test-results',{recursive:true});for(const route of [`/preventivas/${vehicleId}`,`/preventivas?vehicle=${vehicleId}`,`/?vehicle=${vehicleId}`]){await page.goto(base+route);for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/preventives-${route.startsWith('/?')?'dashboard':route.includes('?')?'list':'detail'}-${width}.png`,fullPage:true,caret:'initial'});}}
  const config=await getVehicleInspection(db,v);const payload=(mileage:number)=>({driverIdentification:tag,mileage,configVersion:config.version,submissionKey:crypto.randomUUID(),answers:config.items.map(i=>({item:i.id,answer:'OK',notes:''}))});
  const send=async(data:object)=>{const response=await page.request.post(`${base}/api/checklist/${v.qrToken}`,{headers:{origin:base},data});if(response.status()!==400)return response;const body=await response.json();if(body.code!=='MILEAGE_CONFIRMATION')return response;return page.request.post(`${base}/api/checklist/${v.qrToken}`,{headers:{origin:base},data:{...data,mileageConfirmedAgainst:body.previousMileage}});};
  const atLimit=await send(payload(50000));assert.equal(atLimit.status(),201,await atLimit.text());assert.equal(preventiveState(p,50000).status,'ATTENTION');assert.equal((await db.alert.findUniqueOrThrow({where:{preventivePlanId:p.id}})).priority,'MEDIUM');
  assert.equal((await send(payload(50500))).status(),201);assert.equal((await db.vehicle.findUniqueOrThrow({where:{id:vehicleId}})).mileage,50500);assert.equal((await db.alert.findUniqueOrThrow({where:{preventivePlanId:p.id}})).priority,'HIGH');
  const lower=payload(48000),low=await send(lower);assert.equal(low.status(),201);const lowBody=await low.json();assert.equal(lowBody.mileageWarning,true);const replay=await send(lower);assert.equal((await replay.json()).id,lowBody.id);assert.equal((await db.vehicle.findUniqueOrThrow({where:{id:vehicleId}})).mileage,50500);assert.equal(await db.mileageReading.count({where:{checklistId:lowBody.id}}),1);const reading=await db.mileageReading.findUniqueOrThrow({where:{checklistId:lowBody.id}});assert.equal(reading.accepted,false);assert.equal(reading.previousMileage,50500);assert.equal((await db.checklist.findUniqueOrThrow({where:{id:lowBody.id}})).mileage,48000);assert.ok(await db.alert.findUnique({where:{mileageReadingId:reading.id}}));
  const equal=await send(payload(50500));assert.equal(equal.status(),201);assert.equal((await equal.json()).mileageWarning,false);
  const concurrent=[payload(50600),payload(50700)];const results=await Promise.all(concurrent.map(send));for(let i=0;i<results.length;i++){if(results[i].status()===409)assert.equal((await send(concurrent[i])).status(),201);else assert.equal(results[i].status(),201,await results[i].text());}assert.equal((await db.vehicle.findUniqueOrThrow({where:{id:vehicleId}})).mileage,50700);
  await page.goto(`${base}/checklist/${v.qrToken}`);await page.getByLabel('Matrícula ou identificação').fill(tag);await page.getByLabel('Quilometragem atual').fill('48000');await expect(page.getByText(/KM menor que o último registro/)).toBeVisible();await page.getByLabel('Conferi o hodômetro e confirmo este KM').check();await page.getByRole('button',{name:'Iniciar checklist'}).click();await expect(page.getByRole('button',{name:'Iniciar checklist'})).toHaveCount(0);
  const update={vehicleId,revision:p.revision,mileage:50700,intervalKm:10000,lastMileage:50000,nextMileage:60000,lastAt:null,dueAt:null,toleranceKm:500,toleranceDays:0,upcomingKm:1500,upcomingDays:7,operatorName:'Analista QA',operatorId:tag,note:'Preventiva realizada, novo ciclo'};
  const save=(data:object)=>page.request.post(`${base}/api/admin/preventives`,{headers:{origin:base},data});assert.equal((await save({...update,mileage:10})).status(),400);assert.equal((await save(update)).status(),200);assert.equal((await save(update)).status(),409);p=await db.preventivePlan.findUniqueOrThrow({where:{vehicleId}});assert.equal(p.nextMileage,60000);assert.equal((await db.alert.findUniqueOrThrow({where:{preventivePlanId:p.id}})).status,'COMPLETED');assert.equal(await db.preventivePlanEvent.count({where:{planId:p.id}}),2);assert.equal((await db.alert.findUniqueOrThrow({where:{mileageReadingId:reading.id}})).status,'OPEN');await assert.rejects(db.mileageReading.update({where:{id:reading.id},data:{mileage:50700}}));assert.deepEqual(errors,[]);
  console.log('PASS: configuração UI, próximo KM, 4 estados, tolerâncias, dashboard, leitura maior/igual/menor, alerta, idempotência, concorrência, histórico imutável e 3 larguras.');
 }finally{await browser.close();if(vehicleId)await db.$transaction(async tx=>{await tx.alertEvent.deleteMany({where:{alert:{vehicleId}}});await tx.alert.deleteMany({where:{vehicleId}});await tx.preventivePlanEvent.deleteMany({where:{plan:{vehicleId}}});await tx.preventivePlan.deleteMany({where:{vehicleId}});await tx.mileageReading.deleteMany({where:{vehicleId}});await tx.checklistAnswer.deleteMany({where:{checklist:{vehicleId}}});await tx.checklist.deleteMany({where:{vehicleId}});await tx.vehicle.delete({where:{id:vehicleId}});});assert.equal(JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}})),before,'Frota real preservada');await db.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
