import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {PrismaClient} from '@prisma/client';
import {chromium,expect} from '@playwright/test';
async function main(){
 const db=new PrismaClient(),base='http://127.0.0.1:3000',tag=`QA-${crypto.randomUUID()}`,taxId=`99${String(Date.now()).slice(-12)}`;
 const original=JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}}));const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(45000);await page.emulateMedia({reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let vehicleId:string|undefined;
 try{
  const v=await db.vehicle.create({data:{plate:'ZZZ4Z44',model:'Teste temporário compras',category:'Caminhão',year:2020}});vehicleId=v.id;
  const incident=await db.incident.create({data:{vehicleId,title:tag,description:'Validação de compras'}}),maintenance=await db.maintenance.create({data:{vehicleId,title:tag,type:'Corretiva'}});
  await page.goto(`${base}/compras/nova?vehicle=${vehicleId}`);await page.getByLabel('SC',{exact:true}).fill(tag);await page.getByLabel('Descrição',{exact:true}).fill(tag);await page.getByLabel('Cadastrar solicitante',{exact:true}).check();await page.getByLabel('Nome do solicitante',{exact:true}).fill('Solicitante QA');await page.getByLabel('Matrícula do solicitante',{exact:true}).fill(tag);await page.getByLabel('Cadastrar fornecedor',{exact:true}).check();await page.getByLabel('Razão social',{exact:true}).fill(tag);await page.getByLabel('CNPJ',{exact:true}).fill(taxId);await page.getByLabel('Valor (R$)',{exact:true}).fill('123.45');await page.getByRole('group',{name:'Ocorrências relacionadas',exact:true}).getByRole('checkbox').check();await page.getByRole('group',{name:'Manutenções relacionadas',exact:true}).getByRole('checkbox').check();await page.getByLabel('Motivo / comentário deste atendimento',{exact:true}).fill('Solicitação de teste');await page.getByLabel('Seu nome',{exact:true}).fill('Analista QA');await page.getByLabel('Sua matrícula / identificação',{exact:true}).fill(tag);await page.getByRole('button',{name:'Registrar solicitação',exact:true}).click();await expect(page).toHaveURL(/\/compras\/(?!nova)[^/?]+$/,{timeout:45000});
  const o=await db.purchaseOrder.findFirstOrThrow({where:{vehicleId,description:tag}});assert.equal(o.orderNumber,null);assert.equal(o.stage,'PENDING');assert.equal((await db.incident.findUniqueOrThrow({where:{id:incident.id}})).purchaseOrderId,o.id);assert.equal((await db.maintenance.findUniqueOrThrow({where:{id:maintenance.id}})).purchaseOrderId,o.id);
  let data={id:o.id,revision:o.revision,submissionKey:o.submissionKey!,orderNumber:null as string|null,scNumber:tag,description:tag,stage:'PENDING',vehicleId,equipmentId:null,supplierId:o.supplierId,requesterId:o.requesterId,responsibleId:o.requesterId,amount:123.45,requestedAt:o.requestedAt.toISOString(),staleAfterDays:5,notes:'Observação de teste',incidentIds:[incident.id],maintenanceIds:[maintenance.id],operatorName:'Analista QA',operatorId:tag,note:'Atendimento de teste'};
  const send=(body:object,origin=base)=>page.request.post(`${base}/api/admin/purchases`,{headers:{origin},data:body});
  assert.equal((await send(data,'https://invalid.example')).status(),403);let response=await send(data);assert.equal(response.status(),200,await response.text());data.revision=(await response.json()).revision;assert.equal((await db.purchaseOrder.findUniqueOrThrow({where:{id:o.id}})).stageChangedAt.toISOString(),o.stageChangedAt.toISOString());assert.equal((await send({...data,revision:0})).status(),409);
  for(const stage of ['APPROVAL','APPROVED','REJECTED','CONTINGENCY','ORDERED','WAITING_SUPPLIER','DELIVERED','FINISHED']){data={...data,stage,orderNumber:['ORDERED','WAITING_SUPPLIER','DELIVERED','FINISHED'].includes(stage)?tag:null};response=await send(data);assert.equal(response.status(),200,await response.text());data.revision=(await response.json()).revision;assert.equal((await db.purchaseOrder.findUniqueOrThrow({where:{id:o.id}})).stage,stage);}
  const done=await db.purchaseOrder.findUniqueOrThrow({where:{id:o.id}});assert.equal(done.status,'COMPLETED');assert.ok(await db.purchaseEvent.count({where:{purchaseId:o.id}})>=18);const first=await db.purchaseEvent.findFirstOrThrow({where:{purchaseId:o.id},orderBy:{createdAt:'asc'}});await assert.rejects(db.purchaseEvent.update({where:{id:first.id},data:{note:'Sobrescrever'}}));
  // Edits from an existing module must invalidate a stale purchase form and enter its history.
  await db.maintenance.update({where:{id:maintenance.id},data:{purchaseOrderId:null}});assert.equal((await send(data)).status(),409);const afterLink=await db.purchaseOrder.findUniqueOrThrow({where:{id:o.id}});assert.ok(afterLink.revision>data.revision);assert.ok(await db.purchaseEvent.count({where:{purchaseId:o.id,note:{contains:'Manutenções'}}})>0);
  const race=await Promise.all([send({...data,revision:afterLink.revision,maintenanceIds:[],note:'Primeiro atendimento simultâneo'}),send({...data,revision:afterLink.revision,maintenanceIds:[],note:'Segundo atendimento simultâneo'})]);assert.deepEqual(race.map(r=>r.status()).sort(),[200,409]);
  const {id:_id,revision:_revision,...creation}=data;void _id;void _revision;
  const equipmentData={...creation,submissionKey:crypto.randomUUID(),stage:'PENDING',orderNumber:null,vehicleId:null,newEquipment:{code:`${tag}-E`,name:'Equipamento QA'},incidentIds:[],maintenanceIds:[]};const a=await send(equipmentData),b=await send(equipmentData);assert.equal(a.status(),201,await a.text());assert.equal((await a.json()).id,(await b.json()).id);
  assert.equal((await send({...creation,submissionKey:crypto.randomUUID(),orderNumber:tag,incidentIds:[],maintenanceIds:[]})).status(),409);
  assert.equal((await send({...creation,submissionKey:crypto.randomUUID(),orderNumber:null,stage:'PENDING',vehicleId:null,equipmentId:null,incidentIds:[incident.id],maintenanceIds:[]})).status(),400);
  assert.equal((await send({...creation,submissionKey:crypto.randomUUID(),orderNumber:null,stage:'PENDING'})).status(),400);
  const stale=await db.purchaseOrder.create({data:{number:`SOL-${tag}`,vehicleId,description:`${tag} parada`,amount:0,stageChangedAt:new Date(Date.now()-6*86400000),requesterId:o.requesterId}});
  const staleData={...data,id:stale.id,revision:stale.revision,submissionKey:crypto.randomUUID(),stage:'PENDING',orderNumber:null,incidentIds:[],maintenanceIds:[]};response=await send(staleData);assert.equal(response.status(),200,await response.text());assert.equal((await db.purchaseOrder.findUniqueOrThrow({where:{id:stale.id}})).stageChangedAt.toISOString(),stale.stageChangedAt.toISOString());
  await mkdir('test-results',{recursive:true});for(const [name,route] of [['list',`/compras?q=${tag}&stalled=1`],['detail',`/compras/${stale.id}`]]){await page.goto(base+route);if(name==='list')await expect(page.getByText('Requer acompanhamento · limite de 5 dias',{exact:true})).toBeVisible();else await expect(page.getByText('Solicitação parada há 6 dias neste status.',{exact:true})).toBeVisible();for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/purchases-${name}-${width}.png`,fullPage:true,caret:'initial'});}}
  await page.goto(`${base}/compras?q=${tag}`);await page.getByRole('link',{name:/Aprovado/}).click();await expect(page).toHaveURL(/stage=APPROVED/);await expect(page.getByText(/Nenhuma solicitação encontrada/)).toBeVisible();assert.deepEqual(errors,[]);console.log('PASS: cadastro UI/SC/fornecedor/solicitante, 9 status, vínculos, histórico imutável entre módulos, concorrência, idempotência, equipamento, filtros, atraso e responsividade.');
 }finally{await browser.close();await db.$transaction(async tx=>{
  if(vehicleId){await tx.alertEvent.deleteMany({where:{alert:{vehicleId}}});await tx.alert.deleteMany({where:{vehicleId}});await tx.maintenanceEvent.deleteMany({where:{maintenance:{vehicleId}}});await tx.maintenance.deleteMany({where:{vehicleId}});await tx.incidentEvent.deleteMany({where:{incident:{vehicleId}}});await tx.incident.deleteMany({where:{vehicleId}});}
  const orders=await tx.purchaseOrder.findMany({where:{OR:[{description:{startsWith:tag}},{number:`SOL-${tag}`}]},select:{id:true}});await tx.purchaseEvent.deleteMany({where:{purchaseId:{in:orders.map(o=>o.id)}}});await tx.purchaseOrder.deleteMany({where:{id:{in:orders.map(o=>o.id)}}});await tx.purchaseRequisition.deleteMany({where:{number:tag}});await tx.equipment.deleteMany({where:{code:`${tag}-E`}});await tx.supplier.deleteMany({where:{taxId,name:tag}});await tx.staffMember.deleteMany({where:{employeeId:tag}});if(vehicleId)await tx.vehicle.delete({where:{id:vehicleId}});
 });assert.equal(JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}})),original,'Frota real preservada');await db.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
