import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {chromium,expect,type Page} from '@playwright/test';
import jsQR from 'jsqr';
import {PDFDocument} from 'pdf-lib';
import {prisma as db} from '../src/lib/prisma';
import {getVehicleInspection} from '../src/lib/checklist-config';
async function decode(page:Page,dataUrl:string){const pixels=await page.evaluate(async src=>{const img=new window.Image();img.src=src;await img.decode();const c=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0,c.width,c.height);const bytes=ctx.getImageData(0,0,c.width,c.height).data;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {data:btoa(binary),width:c.width,height:c.height};},dataUrl);return jsQR(new Uint8ClampedArray(Buffer.from(pixels.data,'base64')),pixels.width,pixels.height)?.data;}
async function main(){
 const base='http://127.0.0.1:3000',tag=`QR-${crypto.randomUUID()}`,before=JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}}));const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(60000);await page.emulateMedia({reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.context().addInitScript(()=>{window.print=()=>{};});let vehicleId:string|undefined;
 try{
  const v=await db.vehicle.create({data:{plate:'ZZZ1Z11',model:'VW 19.360 CTC 4X2 - Caminhão de teste',code:'FROTA-TESTE',category:'Caminhão',year:2020,mileage:100}});vehicleId=v.id;const endpoint=`${base}/api/admin/vehicles/${v.id}/qr`;
  const first=await page.request.get(endpoint);assert.equal(first.status(),200);assert.match(first.headers()['cache-control'],/no-store/);const qr=await first.json();assert.ok(qr.url.endsWith(`/checklist/${v.qrToken}`));assert.equal((await (await page.request.get(endpoint)).json()).url,qr.url);assert.equal(await decode(page,qr.image),qr.url);assert.equal((await db.vehicle.findUniqueOrThrow({where:{id:v.id}})).updatedAt.toISOString(),v.updatedAt.toISOString());
  await page.goto(`${base}/checklist/${v.plate}`);await expect(page.getByText('Leia o QR Code atualizado do veículo')).toBeVisible();assert.equal(await page.getByRole('button',{name:'Iniciar checklist'}).count(),0);assert.ok(!(await page.content()).includes(v.qrToken));assert.equal(await page.getByRole('navigation').count(),0);
  const config=await getVehicleInspection(db,v);assert.ok(config.items.length);const payload={driverIdentification:tag,mileage:101,submissionKey:crypto.randomUUID(),configVersion:config.version,answers:config.items.map(i=>({item:i.id,answer:'OK',notes:''}))};
  const send=(token:string,body=payload)=>page.request.post(`${base}/api/checklist/${token}`,{headers:{origin:base},data:body});assert.equal((await send(v.plate)).status(),404);assert.equal((await send('0'.repeat(64))).status(),404);assert.equal((await send(v.qrToken)).status(),201);const saved=await db.checklist.findUniqueOrThrow({where:{submissionKey:payload.submissionKey}});
  const driver=await page.context().newPage();await driver.goto(`${base}/checklist/${v.qrToken}`);await expect(driver.getByLabel('Matrícula ou identificação')).toBeVisible();assert.equal(await driver.getByRole('navigation').count(),0);assert.equal(await driver.locator('a[href="/frota"],a[href="/configuracoes"]').count(),0);
  await page.goto(`${base}/frota/${v.plate}`);await page.getByRole('button',{name:'Visualizar QR Code'}).click();await expect(page.getByAltText('QR Code seguro do checklist')).toBeVisible();
  await mkdir('test-results',{recursive:true});const downloadWait=page.waitForEvent('download');await page.getByRole('link',{name:'PDF / etiqueta 100 × 150 mm',exact:true}).click();const download=await downloadWait;await download.saveAs('test-results/qr-label.pdf');
  for(const size of ['label','a4'] as const){const path=`test-results/qr-${size}.pdf`;if(size==='a4'){const response=await page.request.get(`${endpoint}?format=pdf&size=a4&revision=0`);assert.equal(response.status(),200);await writeFile(path,await response.body());}const pdf=await PDFDocument.load(await readFile(path));assert.equal(pdf.getPageCount(),1);const expected=size==='label'?[100,150]:[210,297];assert.ok(Math.abs(pdf.getPage(0).getWidth()-expected[0]*72/25.4)<.01);assert.ok(Math.abs(pdf.getPage(0).getHeight()-expected[1]*72/25.4)<.01);
   execFileSync(process.env.QR_PYTHON??'python',['-c','import pypdfium2 as p,sys; d=p.PdfDocument(sys.argv[1]); d[0].render(scale=2.5).to_pil().save(sys.argv[2])',path,`test-results/qr-${size}.png`]);assert.equal(await decode(page,`data:image/png;base64,${(await readFile(`test-results/qr-${size}.png`)).toString('base64')}`),qr.url,`QR decodificado do PDF ${size}`);
  }
  const popupWait=page.waitForEvent('popup');await page.getByRole('link',{name:'Imprimir',exact:true}).click();const print=await popupWait;await expect(print.getByRole('button',{name:'Imprimir etiqueta'})).toBeVisible();await print.emulateMedia({media:'print'});await print.screenshot({path:'test-results/qr-print.png',fullPage:true,caret:'initial'});await print.close();
  for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#qr-checklist').screenshot({path:`test-results/qr-panel-${width}.png`});}
  await page.getByText('Regenerar token',{exact:true}).click();await page.getByLabel('Responsável pela regeneração').fill('Analista QR');await page.getByLabel('Matrícula / identificação',{exact:true}).fill(tag);await page.getByLabel('Motivo',{exact:true}).fill('Substituição de etiqueta após validação');await page.getByLabel('Confirmo que as etiquetas antigas deverão ser substituídas.').check();await page.getByRole('button',{name:'Regenerar token e invalidar anteriores'}).click();await expect.poll(async()=>(await db.vehicle.findUniqueOrThrow({where:{id:v.id}})).qrRevision,{timeout:60000}).toBe(1);
  const rotated=await db.vehicle.findUniqueOrThrow({where:{id:v.id}});assert.match(rotated.qrToken,/^[a-f0-9]{64}$/);assert.notEqual(rotated.qrToken,v.qrToken);assert.equal((await page.request.get(`${endpoint}?format=pdf&revision=0`)).status(),409);assert.equal((await send(v.qrToken,{...payload,submissionKey:crypto.randomUUID()})).status(),404);assert.equal((await send(v.qrToken)).status(),404,'Token revogado não pode consultar reenvio');assert.equal((await send(rotated.qrToken,{...payload,submissionKey:crypto.randomUUID()})).status(),201);await driver.reload();await expect(driver.getByText('QR Code inválido ou substituído',{exact:true})).toBeVisible();assert.equal(await driver.getByRole('link').count(),0);await driver.close();
  assert.deepEqual(await db.checklist.findUniqueOrThrow({where:{id:saved.id}}),saved);const events=await db.vehicleQrEvent.findMany({where:{vehicleId}});assert.equal(events.length,1);assert.ok(!JSON.stringify(events).includes(v.qrToken));await assert.rejects(db.vehicleQrEvent.update({where:{id:events[0].id},data:{reason:'Sobrescrita'}}));
  const rotation={revision:1,operatorName:'Analista QR',operatorId:tag,reason:'Rotação concorrente validada',acknowledged:true};const post=(data:object,origin=base)=>page.request.post(endpoint,{headers:{origin},data});assert.equal((await post({...rotation,acknowledged:false})).status(),400);assert.equal((await post(rotation,'https://invalid.example')).status(),403);const race=await Promise.all([post(rotation),post(rotation)]);assert.deepEqual(race.map(r=>r.status()).sort(),[200,409]);assert.equal(await db.vehicleQrEvent.count({where:{vehicleId}}),2);assert.deepEqual(errors,[]);
  console.log('PASS: QR único e estável, decodificação PNG/PDF etiqueta/A4, impressão, três larguras, token obrigatório, revogação, concorrência, histórico e checklists preservados.');
 }finally{await browser.close();if(vehicleId)await db.$transaction(async tx=>{await tx.vehicleQrEvent.deleteMany({where:{vehicleId}});await tx.alertEvent.deleteMany({where:{alert:{vehicleId}}});await tx.alert.deleteMany({where:{vehicleId}});await tx.mileageReading.deleteMany({where:{vehicleId}});await tx.checklist.deleteMany({where:{vehicleId}});await tx.vehicle.delete({where:{id:vehicleId}});});assert.equal(JSON.stringify(await db.vehicle.findMany({orderBy:{id:'asc'}})),before,'Frota real preservada');await db.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
